# This file has been generated by node2nix 1.11.1. Do not edit!

{ nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? [ ] }:

let
  sources = {
    "@esbuild/linux-loong64-0.14.54" = {
      name = "_at_esbuild_slash_linux-loong64";
      packageName = "@esbuild/linux-loong64";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/linux-loong64/-/linux-loong64-0.14.54.tgz";
        sha512 = "bZBrLAIX1kpWelV0XemxBZllyRmM6vgFQQG2GdNb+r3Fkp0FOh1NJSvekXDs7jq70k4euu1cryLMfU+mTXlEpw==";
      };
    };
    "@fastify/ajv-compiler-1.1.0" = {
      name = "_at_fastify_slash_ajv-compiler";
      packageName = "@fastify/ajv-compiler";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fastify/ajv-compiler/-/ajv-compiler-1.1.0.tgz";
        sha512 = "gvCOUNpXsWrIQ3A4aXCLIdblL0tDq42BG/2Xw7oxbil9h11uow10ztS2GuFazNBfjbrsZ5nl+nPl5jDSjj5TSg==";
      };
    };
    "@fastify/error-2.0.0" = {
      name = "_at_fastify_slash_error";
      packageName = "@fastify/error";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fastify/error/-/error-2.0.0.tgz";
        sha512 = "wI3fpfDT0t7p8E6dA2eTECzzOd+bZsZCJ2Hcv+Onn2b7ZwK3RwD27uW2QDaMtQhAfWQQP+WNK7nKf0twLsBf9w==";
      };
    };
    "@fastify/static-5.0.2" = {
      name = "_at_fastify_slash_static";
      packageName = "@fastify/static";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fastify/static/-/static-5.0.2.tgz";
        sha512 = "HvyXZ5a7hUHoSBRq9jKUuKIUCkHMkCDcmiAeEmixXlGOx8pEWx3NYOIaiivcjWa6/NLvfdUT+t/jzfVQ2PA7Gw==";
      };
    };
    "@sindresorhus/is-5.3.0" = {
      name = "_at_sindresorhus_slash_is";
      packageName = "@sindresorhus/is";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sindresorhus/is/-/is-5.3.0.tgz";
        sha512 = "CX6t4SYQ37lzxicAqsBtxA3OseeoVrh9cSJ5PFYam0GksYlupRfy1A+Q4aYD3zvcfECLc0zO2u+ZnR2UYKvCrw==";
      };
    };
    "@szmarczak/http-timer-5.0.1" = {
      name = "_at_szmarczak_slash_http-timer";
      packageName = "@szmarczak/http-timer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@szmarczak/http-timer/-/http-timer-5.0.1.tgz";
        sha512 = "+PmQX0PiAYPMeVYe237LJAYvOMYW1j2rH5YROyS3b4CTVJum34HfRvKvAzozHAQG0TnHNdUfY9nCeUyRAs//cw==";
      };
    };
    "@types/http-cache-semantics-4.0.1" = {
      name = "_at_types_slash_http-cache-semantics";
      packageName = "@types/http-cache-semantics";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/http-cache-semantics/-/http-cache-semantics-4.0.1.tgz";
        sha512 = "SZs7ekbP8CN0txVG2xVRH6EgKmEm31BOxA07vkFaETzZz1xh+cbt8BcI0slpymvwhx5dlFnQG2rTlPVQn+iRPQ==";
      };
    };
    "abstract-logging-2.0.1" = {
      name = "abstract-logging";
      packageName = "abstract-logging";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abstract-logging/-/abstract-logging-2.0.1.tgz";
        sha512 = "2BjRTZxTPvheOvGbBslFSYOUkr+SjPtOnrLP33f+VIWLzezQpZcqVg7ja3L4dBXmzzgwT+a029jRx5PCi3JuiA==";
      };
    };
    "ajv-6.12.6" = {
      name = "ajv";
      packageName = "ajv";
      version = "6.12.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-6.12.6.tgz";
        sha512 = "j3fVLgvTo527anyYyJOGTYJbG+vnnQYvE0m5mmkc1TK+nxAppkCLMIL0aZ4dblVCNoGShhm+kzE4ZUykBoMg4g==";
      };
    };
    "ajv-8.11.2" = {
      name = "ajv";
      packageName = "ajv";
      version = "8.11.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-8.11.2.tgz";
        sha512 = "E4bfmKAhGiSTvMfL1Myyycaub+cUEU2/IvpylXkUu7CHBkBj1f/ikdzbD7YQ6FKUbixDxeYvB/xY4fvyroDlQg==";
      };
    };
    "archy-1.0.0" = {
      name = "archy";
      packageName = "archy";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/archy/-/archy-1.0.0.tgz";
        sha512 = "Xg+9RwCg/0p32teKdGMPTPnVXKD0w3DfHnFTficozsAgsvq2XenPJq/MYpzzQ/v8zrOyJn6Ds39VA4JIDwFfqw==";
      };
    };
    "atomic-sleep-1.0.0" = {
      name = "atomic-sleep";
      packageName = "atomic-sleep";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/atomic-sleep/-/atomic-sleep-1.0.0.tgz";
        sha512 = "kNOjDqAh7px0XWNI+4QbzoiR/nTkHAWNud2uvnJquD1/x5a7EQZMJT0AczqK0Qn67oY/TTQ1LbUKajZpp3I9tQ==";
      };
    };
    "avvio-7.2.5" = {
      name = "avvio";
      packageName = "avvio";
      version = "7.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/avvio/-/avvio-7.2.5.tgz";
        sha512 = "AOhBxyLVdpOad3TujtC9kL/9r3HnTkxwQ5ggOsYrvvZP1cCFvzHWJd5XxZDFuTn+IN8vkKSG5SEJrd27vCSbeA==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "cacheable-lookup-7.0.0" = {
      name = "cacheable-lookup";
      packageName = "cacheable-lookup";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cacheable-lookup/-/cacheable-lookup-7.0.0.tgz";
        sha512 = "+qJyx4xiKra8mZrcwhjMRMUhD5NR1R8esPkzIYxX96JiecFoxAXFuz/GpR3+ev4PE1WamHip78wV0vcmPQtp8w==";
      };
    };
    "cacheable-request-10.2.2" = {
      name = "cacheable-request";
      packageName = "cacheable-request";
      version = "10.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cacheable-request/-/cacheable-request-10.2.2.tgz";
        sha512 = "KxjQZM3UIo7/J6W4sLpwFvu1GB3Whv8NtZ8ZrUL284eiQjiXeeqWTdhixNrp/NLZ/JNuFBo6BD4ZaO8ZJ5BN8Q==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha512 = "/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==";
      };
    };
    "content-disposition-0.5.4" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.4.tgz";
        sha512 = "FveZTNuGw04cxlAiWbzi6zTAL/lhehaWbTtgluJh4/E95DqMwTmha3KZN1aAWA8cFIhHzMZUvLevkw5Rqk+tSQ==";
      };
    };
    "cookie-0.5.0" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.5.0.tgz";
        sha512 = "YZ3GUyn/o8gfKJlnlX7g7xq4gyO6OSuhGPKaaGssGB2qgDUS0gPgtTvoyZLTt9Ab6dC4hfc9dV5arkvc/OCmrw==";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "debug-4.3.4" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz";
        sha512 = "PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==";
      };
    };
    "decompress-response-6.0.0" = {
      name = "decompress-response";
      packageName = "decompress-response";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-response/-/decompress-response-6.0.0.tgz";
        sha512 = "aW35yZM6Bb/4oJlZncMH2LCoZtJXTRxES17vE3hoRiowU2kWHaJKFkSBDnDR+cm9J+9QhXmREyIfv0pji9ejCQ==";
      };
    };
    "deepmerge-4.2.2" = {
      name = "deepmerge";
      packageName = "deepmerge";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/deepmerge/-/deepmerge-4.2.2.tgz";
        sha512 = "FJ3UgI4gIl+PHZm53knsuSFpE+nESMr7M4v9QcgB7S63Kj/6WqMiFQJpBBYz1Pt+66bZpP3Q7Lye0Oo9MPKEdg==";
      };
    };
    "defer-to-connect-2.0.1" = {
      name = "defer-to-connect";
      packageName = "defer-to-connect";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/defer-to-connect/-/defer-to-connect-2.0.1.tgz";
        sha512 = "4tvttepXG1VaYGrRibk5EwJd1t4udunSOVMdLSAL6mId1ix438oPwPZMALY41FCijukO1L0twNcGsdzS7dHgDg==";
      };
    };
    "depd-1.1.2" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz";
        sha512 = "7emPTl6Dpo6JRXOXjLRxck+FlLRX5847cLKEn00PLAgc3g2hTZZgr+e4c2v6QpSmLeFP3n5yUo7ft6avBK/5jQ==";
      };
    };
    "destroy-1.0.4" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz";
        sha512 = "3NdhDuEXnfun/z7x9GOElY49LoqVHoGScmOKwmxhsS8N5Y+Z8KyPPDnaSzqWgYt/ji4mqwfTS34Htrk0zPIXVg==";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha512 = "WMwm9LhRUo+WUaRN+vRuETqG89IgZphVSNkdFgeb6sS/E4OrDIN7t48CAewSHXc6C8lefD8KKfr5vY61brQlow==";
      };
    };
    "encodeurl-1.0.2" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.2.tgz";
        sha512 = "TPJXq8JqFaVYm2CWmPvnP2Iyo4ZSM7/QKcSmuMLDObfpH5fi7RUGmd/rTDf+rut/saiDiQEeVTNgAmJEdAOx0w==";
      };
    };
    "encoding-negotiator-2.0.1" = {
      name = "encoding-negotiator";
      packageName = "encoding-negotiator";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/encoding-negotiator/-/encoding-negotiator-2.0.1.tgz";
        sha512 = "GSK7qphNR4iPcejfAlZxKDoz3xMhnspwImK+Af5WhePS9jUpK/Oh7rUdyENWu+9rgDflOCTmAojBsgsvM8neAQ==";
      };
    };
    "esbuild-0.14.54" = {
      name = "esbuild";
      packageName = "esbuild";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild/-/esbuild-0.14.54.tgz";
        sha512 = "Cy9llcy8DvET5uznocPyqL3BFRrFXSVqbgpMJ9Wz8oVjZlh/zUSNbPRbov0VX7VxN2JH1Oa0uNxZ7eLRb62pJA==";
      };
    };
    "esbuild-android-64-0.14.54" = {
      name = "esbuild-android-64";
      packageName = "esbuild-android-64";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-android-64/-/esbuild-android-64-0.14.54.tgz";
        sha512 = "Tz2++Aqqz0rJ7kYBfz+iqyE3QMycD4vk7LBRyWaAVFgFtQ/O8EJOnVmTOiDWYZ/uYzB4kvP+bqejYdVKzE5lAQ==";
      };
    };
    "esbuild-android-arm64-0.14.54" = {
      name = "esbuild-android-arm64";
      packageName = "esbuild-android-arm64";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-android-arm64/-/esbuild-android-arm64-0.14.54.tgz";
        sha512 = "F9E+/QDi9sSkLaClO8SOV6etqPd+5DgJje1F9lOWoNncDdOBL2YF59IhsWATSt0TLZbYCf3pNlTHvVV5VfHdvg==";
      };
    };
    "esbuild-darwin-64-0.14.54" = {
      name = "esbuild-darwin-64";
      packageName = "esbuild-darwin-64";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-darwin-64/-/esbuild-darwin-64-0.14.54.tgz";
        sha512 = "jtdKWV3nBviOd5v4hOpkVmpxsBy90CGzebpbO9beiqUYVMBtSc0AL9zGftFuBon7PNDcdvNCEuQqw2x0wP9yug==";
      };
    };
    "esbuild-darwin-arm64-0.14.54" = {
      name = "esbuild-darwin-arm64";
      packageName = "esbuild-darwin-arm64";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-darwin-arm64/-/esbuild-darwin-arm64-0.14.54.tgz";
        sha512 = "OPafJHD2oUPyvJMrsCvDGkRrVCar5aVyHfWGQzY1dWnzErjrDuSETxwA2HSsyg2jORLY8yBfzc1MIpUkXlctmw==";
      };
    };
    "esbuild-freebsd-64-0.14.54" = {
      name = "esbuild-freebsd-64";
      packageName = "esbuild-freebsd-64";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-freebsd-64/-/esbuild-freebsd-64-0.14.54.tgz";
        sha512 = "OKwd4gmwHqOTp4mOGZKe/XUlbDJ4Q9TjX0hMPIDBUWWu/kwhBAudJdBoxnjNf9ocIB6GN6CPowYpR/hRCbSYAg==";
      };
    };
    "esbuild-freebsd-arm64-0.14.54" = {
      name = "esbuild-freebsd-arm64";
      packageName = "esbuild-freebsd-arm64";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-freebsd-arm64/-/esbuild-freebsd-arm64-0.14.54.tgz";
        sha512 = "sFwueGr7OvIFiQT6WeG0jRLjkjdqWWSrfbVwZp8iMP+8UHEHRBvlaxL6IuKNDwAozNUmbb8nIMXa7oAOARGs1Q==";
      };
    };
    "esbuild-linux-32-0.14.54" = {
      name = "esbuild-linux-32";
      packageName = "esbuild-linux-32";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-32/-/esbuild-linux-32-0.14.54.tgz";
        sha512 = "1ZuY+JDI//WmklKlBgJnglpUL1owm2OX+8E1syCD6UAxcMM/XoWd76OHSjl/0MR0LisSAXDqgjT3uJqT67O3qw==";
      };
    };
    "esbuild-linux-64-0.14.54" = {
      name = "esbuild-linux-64";
      packageName = "esbuild-linux-64";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.14.54.tgz";
        sha512 = "EgjAgH5HwTbtNsTqQOXWApBaPVdDn7XcK+/PtJwZLT1UmpLoznPd8c5CxqsH2dQK3j05YsB3L17T8vE7cp4cCg==";
      };
    };
    "esbuild-linux-arm-0.14.54" = {
      name = "esbuild-linux-arm";
      packageName = "esbuild-linux-arm";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-arm/-/esbuild-linux-arm-0.14.54.tgz";
        sha512 = "qqz/SjemQhVMTnvcLGoLOdFpCYbz4v4fUo+TfsWG+1aOu70/80RV6bgNpR2JCrppV2moUQkww+6bWxXRL9YMGw==";
      };
    };
    "esbuild-linux-arm64-0.14.54" = {
      name = "esbuild-linux-arm64";
      packageName = "esbuild-linux-arm64";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-arm64/-/esbuild-linux-arm64-0.14.54.tgz";
        sha512 = "WL71L+0Rwv+Gv/HTmxTEmpv0UgmxYa5ftZILVi2QmZBgX3q7+tDeOQNqGtdXSdsL8TQi1vIaVFHUPDe0O0kdig==";
      };
    };
    "esbuild-linux-mips64le-0.14.54" = {
      name = "esbuild-linux-mips64le";
      packageName = "esbuild-linux-mips64le";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-mips64le/-/esbuild-linux-mips64le-0.14.54.tgz";
        sha512 = "qTHGQB8D1etd0u1+sB6p0ikLKRVuCWhYQhAHRPkO+OF3I/iSlTKNNS0Lh2Oc0g0UFGguaFZZiPJdJey3AGpAlw==";
      };
    };
    "esbuild-linux-ppc64le-0.14.54" = {
      name = "esbuild-linux-ppc64le";
      packageName = "esbuild-linux-ppc64le";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-ppc64le/-/esbuild-linux-ppc64le-0.14.54.tgz";
        sha512 = "j3OMlzHiqwZBDPRCDFKcx595XVfOfOnv68Ax3U4UKZ3MTYQB5Yz3X1mn5GnodEVYzhtZgxEBidLWeIs8FDSfrQ==";
      };
    };
    "esbuild-linux-riscv64-0.14.54" = {
      name = "esbuild-linux-riscv64";
      packageName = "esbuild-linux-riscv64";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-riscv64/-/esbuild-linux-riscv64-0.14.54.tgz";
        sha512 = "y7Vt7Wl9dkOGZjxQZnDAqqn+XOqFD7IMWiewY5SPlNlzMX39ocPQlOaoxvT4FllA5viyV26/QzHtvTjVNOxHZg==";
      };
    };
    "esbuild-linux-s390x-0.14.54" = {
      name = "esbuild-linux-s390x";
      packageName = "esbuild-linux-s390x";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-linux-s390x/-/esbuild-linux-s390x-0.14.54.tgz";
        sha512 = "zaHpW9dziAsi7lRcyV4r8dhfG1qBidQWUXweUjnw+lliChJqQr+6XD71K41oEIC3Mx1KStovEmlzm+MkGZHnHA==";
      };
    };
    "esbuild-netbsd-64-0.14.54" = {
      name = "esbuild-netbsd-64";
      packageName = "esbuild-netbsd-64";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-netbsd-64/-/esbuild-netbsd-64-0.14.54.tgz";
        sha512 = "PR01lmIMnfJTgeU9VJTDY9ZerDWVFIUzAtJuDHwwceppW7cQWjBBqP48NdeRtoP04/AtO9a7w3viI+PIDr6d+w==";
      };
    };
    "esbuild-openbsd-64-0.14.54" = {
      name = "esbuild-openbsd-64";
      packageName = "esbuild-openbsd-64";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-openbsd-64/-/esbuild-openbsd-64-0.14.54.tgz";
        sha512 = "Qyk7ikT2o7Wu76UsvvDS5q0amJvmRzDyVlL0qf5VLsLchjCa1+IAvd8kTBgUxD7VBUUVgItLkk609ZHUc1oCaw==";
      };
    };
    "esbuild-sunos-64-0.14.54" = {
      name = "esbuild-sunos-64";
      packageName = "esbuild-sunos-64";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-sunos-64/-/esbuild-sunos-64-0.14.54.tgz";
        sha512 = "28GZ24KmMSeKi5ueWzMcco6EBHStL3B6ubM7M51RmPwXQGLe0teBGJocmWhgwccA1GeFXqxzILIxXpHbl9Q/Kw==";
      };
    };
    "esbuild-windows-32-0.14.54" = {
      name = "esbuild-windows-32";
      packageName = "esbuild-windows-32";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-32/-/esbuild-windows-32-0.14.54.tgz";
        sha512 = "T+rdZW19ql9MjS7pixmZYVObd9G7kcaZo+sETqNH4RCkuuYSuv9AGHUVnPoP9hhuE1WM1ZimHz1CIBHBboLU7w==";
      };
    };
    "esbuild-windows-64-0.14.54" = {
      name = "esbuild-windows-64";
      packageName = "esbuild-windows-64";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.14.54.tgz";
        sha512 = "AoHTRBUuYwXtZhjXZbA1pGfTo8cJo3vZIcWGLiUcTNgHpJJMC1rVA44ZereBHMJtotyN71S8Qw0npiCIkW96cQ==";
      };
    };
    "esbuild-windows-arm64-0.14.54" = {
      name = "esbuild-windows-arm64";
      packageName = "esbuild-windows-arm64";
      version = "0.14.54";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild-windows-arm64/-/esbuild-windows-arm64-0.14.54.tgz";
        sha512 = "M0kuUvXhot1zOISQGXwWn6YtS+Y/1RT9WrVIOywZnJHo3jCDyewAc79aKNQWFCQm+xNHVTq9h8dZKvygoXQQRg==";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha512 = "NiSupZ4OeuGwr68lGIeym/ksIZMJodUGOSCZ/FSnTxcrekbvqrgdUxlJOMpijaKZVjAJrWrGs/6Jy8OMuyj9ow==";
      };
    };
    "etag-1.8.1" = {
      name = "etag";
      packageName = "etag";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.8.1.tgz";
        sha512 = "aIL5Fx7mawVa300al2BnEE4iNvo1qETxLrPI/o05L7z6go7fCw1J6EQmbK4FmJ2AS7kgVF/KEZWufBfdClMcPg==";
      };
    };
    "fast-decode-uri-component-1.0.1" = {
      name = "fast-decode-uri-component";
      packageName = "fast-decode-uri-component";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-decode-uri-component/-/fast-decode-uri-component-1.0.1.tgz";
        sha512 = "WKgKWg5eUxvRZGwW8FvfbaH7AXSh2cL+3j5fMGzUMCxWBJ3dV3a7Wz8y2f/uQ0e3B6WmodD3oS54jTQ9HVTIIg==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fast-json-stable-stringify-2.1.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz";
        sha512 = "lhd/wF+Lk98HZoTCtlVraHtfh5XYijIjalXck7saUtuanSDyLMxnHhSXEDJqHxD7msR8D0uCmqlkwjCV8xvwHw==";
      };
    };
    "fast-json-stringify-2.7.13" = {
      name = "fast-json-stringify";
      packageName = "fast-json-stringify";
      version = "2.7.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stringify/-/fast-json-stringify-2.7.13.tgz";
        sha512 = "ar+hQ4+OIurUGjSJD1anvYSDcUflywhKjfxnsW4TBTD7+u0tJufv6DKRWoQk3vI6YBOWMoz0TQtfbe7dxbQmvA==";
      };
    };
    "fast-redact-3.1.2" = {
      name = "fast-redact";
      packageName = "fast-redact";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-redact/-/fast-redact-3.1.2.tgz";
        sha512 = "+0em+Iya9fKGfEQGcd62Yv6onjBmmhV1uh86XVfOU8VwAe6kaFdQCWI9s0/Nnugx5Vd9tdbZ7e6gE2tR9dzXdw==";
      };
    };
    "fast-safe-stringify-2.1.1" = {
      name = "fast-safe-stringify";
      packageName = "fast-safe-stringify";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-safe-stringify/-/fast-safe-stringify-2.1.1.tgz";
        sha512 = "W+KJc2dmILlPplD/H4K9l9LcAHAfPtP6BY84uVLXQ6Evcz9Lcg33Y2z1IVblT6xdY54PXYVHEv+0Wpq8Io6zkA==";
      };
    };
    "fastify-3.29.3" = {
      name = "fastify";
      packageName = "fastify";
      version = "3.29.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastify/-/fastify-3.29.3.tgz";
        sha512 = "PA5mGkVnAnhysmyAnXMN9gdOlcfIxyGsfj9C7/a3sSfe5mC38euEGRLEB0T7ygbi7TIZ9yIZ/FLiERpwZeWriA==";
      };
    };
    "fastify-plugin-3.0.1" = {
      name = "fastify-plugin";
      packageName = "fastify-plugin";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastify-plugin/-/fastify-plugin-3.0.1.tgz";
        sha512 = "qKcDXmuZadJqdTm6vlCqioEbyewF60b/0LOFCcYN1B6BIZGlYJumWWOYs70SFYLDAH4YqdE1cxH/RKMG7rFxgA==";
      };
    };
    "fastq-1.13.0" = {
      name = "fastq";
      packageName = "fastq";
      version = "1.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastq/-/fastq-1.13.0.tgz";
        sha512 = "YpkpUnK8od0o1hmeSc7UUs/eB/vIPWJYjKck2QKIzAf71Vm1AAQ3EbuZB3g2JIy+pg+ERD0vqI79KyZiB2e2Nw==";
      };
    };
    "find-my-way-4.5.1" = {
      name = "find-my-way";
      packageName = "find-my-way";
      version = "4.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-my-way/-/find-my-way-4.5.1.tgz";
        sha512 = "kE0u7sGoUFbMXcOG/xpkmz4sRLCklERnBcg7Ftuu1iAxsfEt2S46RLJ3Sq7vshsEy2wJT2hZxE58XZK27qa8kg==";
      };
    };
    "flatstr-1.0.12" = {
      name = "flatstr";
      packageName = "flatstr";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/flatstr/-/flatstr-1.0.12.tgz";
        sha512 = "4zPxDyhCyiN2wIAtSLI6gc82/EjqZc1onI4Mz/l0pWrAlsSfYH/2ZIcU+e3oA2wDwbzIWNKwa23F8rh6+DRWkw==";
      };
    };
    "form-data-encoder-2.1.3" = {
      name = "form-data-encoder";
      packageName = "form-data-encoder";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data-encoder/-/form-data-encoder-2.1.3.tgz";
        sha512 = "KqU0nnPMgIJcCOFTNJFEA8epcseEaoox4XZffTgy8jlI6pL/5EFyR54NRG7CnCJN0biY7q52DO3MH6/sJ/TKlQ==";
      };
    };
    "forwarded-0.2.0" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.2.0.tgz";
        sha512 = "buRG0fpBtRHSTCOASe6hD258tEubFoRLb4ZNA6NxMVHNw2gOcwHo9wyablzMzOA5z9xA9L1KNjk/Nt6MT9aYow==";
      };
    };
    "fresh-0.5.2" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.5.2.tgz";
        sha512 = "zJ2mQYM18rEFOudeV4GShTGIQ7RbzA7ozbU9I/XBpm7kqgMywgmylMwXHxZJmkVoYkna9d2pVXVXPdYTP9ej8Q==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha512 = "OO0pH2lK6a0hZnAdau5ItzHPI6pUlvI7jMVnxUQRtw4owF2wk8lOSabtGDCTP4Ggrg2MbGnWO9X8K1t4+fGMDw==";
      };
    };
    "fsevents-2.3.2" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-2.3.2.tgz";
        sha512 = "xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==";
      };
    };
    "get-stream-6.0.1" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-6.0.1.tgz";
        sha512 = "ts6Wi+2j3jQjqi70w5AlN8DFnkSwC+MqmxEzdEALB2qXZYV3X/b1CTfgPLGJNMeAWxdPfU8FO1ms3NUfaHCPYg==";
      };
    };
    "glob-7.2.3" = {
      name = "glob";
      packageName = "glob";
      version = "7.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.2.3.tgz";
        sha512 = "nFR0zLpU2YCaRxwoCJvL6UvCH2JFyFVIvwTLsIf21AuHlMskA1hhTdk+LlYJtOlYt9v6dvszD2BGRqBL+iQK9Q==";
      };
    };
    "got-12.5.3" = {
      name = "got";
      packageName = "got";
      version = "12.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/got/-/got-12.5.3.tgz";
        sha512 = "8wKnb9MGU8IPGRIo+/ukTy9XLJBwDiCpIf5TVzQ9Cpol50eMTpBq2GAuDsuDIz7hTYmZgMgC1e9ydr6kSDWs3w==";
      };
    };
    "http-cache-semantics-4.1.0" = {
      name = "http-cache-semantics";
      packageName = "http-cache-semantics";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-cache-semantics/-/http-cache-semantics-4.1.0.tgz";
        sha512 = "carPklcUh7ROWRK7Cv27RPtdhYhUsela/ue5/jKzjegVvXDqM2ILE9Q2BGn9JZJh1g87cp56su/FgQSzcWS8cQ==";
      };
    };
    "http-errors-1.8.1" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.8.1.tgz";
        sha512 = "Kpk9Sm7NmI+RHhnj6OIWDI1d6fIoFAtFt9RLaTMRlg/8w49juAStsrBgp0Dp4OdxdVbRIeKhtCUvoi/RuAhO4g==";
      };
    };
    "http2-wrapper-2.2.0" = {
      name = "http2-wrapper";
      packageName = "http2-wrapper";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http2-wrapper/-/http2-wrapper-2.2.0.tgz";
        sha512 = "kZB0wxMo0sh1PehyjJUWRFEd99KC5TLjZ2cULC4f9iqJBAmKQQXEICjxl5iPJRwP40dpeHFqqhm7tYCvODpqpQ==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha512 = "k92I/b08q4wvFscXCLvqfsHCrjrF7yiXsQuIVvVE7N82W3+aqpzuUdBbfhWcy/FZR3/4IgflMgKLOsvPDrGCJA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ipaddr.js-1.9.1" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.9.1.tgz";
        sha512 = "0KI/607xoxSToH7GjN1FfSbLoU0+btTicjsQSWQlh/hZykN8KpmMf7uYwPW3R+akZ6R/w18ZlXSHBYXiYUPO3g==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "json-buffer-3.0.1" = {
      name = "json-buffer";
      packageName = "json-buffer";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-buffer/-/json-buffer-3.0.1.tgz";
        sha512 = "4bV5BfR2mqfQTJm+V5tPPdf+ZpuhiIvTuAB5g8kcrXOZpTT/QwwVRWBywX1ozr6lEuPdbHxwaJlm9G6mI2sfSQ==";
      };
    };
    "json-schema-traverse-0.4.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.4.1.tgz";
        sha512 = "xbbCH5dCYU5T8LcEhhuh7HJ88HXuW3qsI3Y0zOZFKfZEHcpWiHU/Jxzk629Brsab/mMiHQti9wMP+845RPe3Vg==";
      };
    };
    "json-schema-traverse-1.0.0" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-1.0.0.tgz";
        sha512 = "NM8/P9n3XjXhIZn1lLhkFaACTOURQXjWhV4BA/RnOv8xvgqtqpAX9IO4mRQxSx1Rlo4tqzeqb0sOlruaOy3dug==";
      };
    };
    "keyv-4.5.2" = {
      name = "keyv";
      packageName = "keyv";
      version = "4.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/keyv/-/keyv-4.5.2.tgz";
        sha512 = "5MHbFaKn8cNSmVW7BYnijeAVlE4cYA/SVkifVgrh7yotnfhKmjuXpDKjrABLnT0SfHWV21P8ow07OGfRrNDg8g==";
      };
    };
    "light-my-request-4.12.0" = {
      name = "light-my-request";
      packageName = "light-my-request";
      version = "4.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/light-my-request/-/light-my-request-4.12.0.tgz";
        sha512 = "0y+9VIfJEsPVzK5ArSIJ8Dkxp8QMP7/aCuxCUtG/tr9a2NoOf/snATE/OUc05XUplJCEnRh6gTkH7xh9POt1DQ==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "lowercase-keys-3.0.0" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-3.0.0.tgz";
        sha512 = "ozCC6gdQ+glXOQsveKD0YsDy8DSQFjDTz4zyzEHNV5+JP5D62LmfDZ6o1cycFx9ouG940M5dE8C8CTewdj2YWQ==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "x0Vn8spI+wuJ1O6S7gnbaQg8Pxh4NNHb7KSINmEWKiPE4RKOplvijn+NkmYmmRgP68mc70j2EbeTFRsrswaQeg==";
      };
    };
    "mimic-response-3.1.0" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-3.1.0.tgz";
        sha512 = "z0yWI+4FDrrweS8Zmt4Ej5HdJmky15+L2e6Wgn3+iK5fWzb6T3fhNFq2+MeTRb064c6Wr4N/wv0DzQTjNzHNGQ==";
      };
    };
    "mimic-response-4.0.0" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-4.0.0.tgz";
        sha512 = "e5ISH9xMYU0DzrT+jl8q2ze9D6eWBto+I8CNpe+VI+K2J/F/k3PdkdTdz4wvGVH4NTpo+NRYTVIuMQEMMcsLqg==";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha512 = "Tpp60P6IUJDTuOq/5Z8cdskzJujfwqfOTkrwIwj7IRISpnkJnT6SyJ4PCPnGMoFjC9ddhal5KVIYtAt97ix05A==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "normalize-url-7.2.0" = {
      name = "normalize-url";
      packageName = "normalize-url";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-url/-/normalize-url-7.2.0.tgz";
        sha512 = "uhXOdZry0L6M2UIo9BTt7FdpBDiAGN/7oItedQwPKh8jh31ZlvC8U9Xl/EJ3aijDHaywXTW3QbZ6LuCocur1YA==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha512 = "ikqdkGAAyf/X/gPhXGvfgAytDZtDbr+bkNUJ0N9h5MI/dmdgCs3l6hoHrcUv41sRKew3jIwrp4qQDXiK99Utww==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "os-paths-7.3.0" = {
      name = "os-paths";
      packageName = "os-paths";
      version = "7.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-paths/-/os-paths-7.3.0.tgz";
        sha512 = "RwE14ySxx9W/wTYzT4F0jUlrhYHLBHVW38os8yN7I9IGmLOpI76NDSlTa7gwHhVnH0IoM6BFp++s5sI3x3dicw==";
      };
    };
    "p-cancelable-3.0.0" = {
      name = "p-cancelable";
      packageName = "p-cancelable";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-cancelable/-/p-cancelable-3.0.0.tgz";
        sha512 = "mlVgR3PGuzlo0MmTdk4cXqXWlwQDLnONTAg6sm62XkMJEiRxN3GL3SffkYvqwonbkJBcrI7Uvv5Zh9yjvn2iUw==";
      };
    };
    "p-limit-3.1.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-3.1.0.tgz";
        sha512 = "TYOanM3wGwNGsZN2cVTYPArw454xnXj5qmWF1bEoAc4+cU/ol7GVh7odevjp1FNHduHc3KZMcFduxU5Xc6uJRQ==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha512 = "AVbw3UJ2e9bq64vSaS9Am0fje1Pa8pbGqTTsmXfaIiMpnr5DlDhfJOuLj9Sf95ZPVDAUerDfEk88MPmPe7UCQg==";
      };
    };
    "pct-encode-1.0.2" = {
      name = "pct-encode";
      packageName = "pct-encode";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pct-encode/-/pct-encode-1.0.2.tgz";
        sha512 = "8W3p1RpEfGKbY68uo/n+FMYf/vIpSiYJhtPCQ3ioxMuKJ8u4Q6j3pIh0LAeszEdPSIguxon8CGjx4aXX33l0Tg==";
      };
    };
    "pino-6.14.0" = {
      name = "pino";
      packageName = "pino";
      version = "6.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pino/-/pino-6.14.0.tgz";
        sha512 = "iuhEDel3Z3hF9Jfe44DPXR8l07bhjuFY3GMHIXbjnY9XcafbyDDwl2sN2vw2GjMPf5Nkoe+OFao7ffn9SXaKDg==";
      };
    };
    "pino-std-serializers-3.2.0" = {
      name = "pino-std-serializers";
      packageName = "pino-std-serializers";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pino-std-serializers/-/pino-std-serializers-3.2.0.tgz";
        sha512 = "EqX4pwDPrt3MuOAAUBMU0Tk5kR/YcCM5fNPEzgCO2zJ5HfX0vbiH9HbJglnyeQsN96Kznae6MWD47pZB5avTrg==";
      };
    };
    "process-warning-1.0.0" = {
      name = "process-warning";
      packageName = "process-warning";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-warning/-/process-warning-1.0.0.tgz";
        sha512 = "du4wfLyj4yCZq1VupnVSZmRsPJsNuxoDQFdCFHLaYiEbFBD7QE0a+I4D7hOxrVnh78QE/YipFAj9lXHiXocV+Q==";
      };
    };
    "proxy-addr-2.0.7" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "2.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-2.0.7.tgz";
        sha512 = "llQsMLSUDUPT44jdrU/O37qlnifitDP+ZwrmmZcoSKyLKvtZxpyV0n2/bD/N4tBAAZ/gJEdZU7KMraoK1+XYAg==";
      };
    };
    "punycode-2.1.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.1.1.tgz";
        sha512 = "XRsRjdf+j5ml+y/6GKHPZbrF/8p2Yga0JPtdqTIY2Xe5ohJPD9saDJJLPvp9+NSBprVvevdXZybnj2cv8OEd0A==";
      };
    };
    "queue-microtask-1.2.3" = {
      name = "queue-microtask";
      packageName = "queue-microtask";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
        sha512 = "NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
      };
    };
    "quick-format-unescaped-4.0.4" = {
      name = "quick-format-unescaped";
      packageName = "quick-format-unescaped";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/quick-format-unescaped/-/quick-format-unescaped-4.0.4.tgz";
        sha512 = "tYC1Q1hgyRuHgloV/YXs2w15unPVh8qfu/qCTfhTYamaw7fyhumKa2yGpdSo87vY32rIclj+4fWYQXUMs9EHvg==";
      };
    };
    "quick-lru-5.1.1" = {
      name = "quick-lru";
      packageName = "quick-lru";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/quick-lru/-/quick-lru-5.1.1.tgz";
        sha512 = "WuyALRjWPDGtt/wzJiadO5AXY+8hZ80hVpe6MyivgraREW751X3SbhRvG3eLKOYN+8VEvqLcf3wdnt44Z4S4SA==";
      };
    };
    "ramda-0.28.0" = {
      name = "ramda";
      packageName = "ramda";
      version = "0.28.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ramda/-/ramda-0.28.0.tgz";
        sha512 = "9QnLuG/kPVgWvMQ4aODhsBUFKOUmnbUnsSXACv+NCQZcHbeb+v8Lodp8OVxtRULN1/xOyYLLaL6npE6dMq5QTA==";
      };
    };
    "range-parser-1.2.1" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.1.tgz";
        sha512 = "Hrgsx+orqoygnmhFbKaHE6c296J+HTAQXoxEF6gNupROmmGJRoyzfG3ccAveqCBrwr/2yxQ5BVd/GTl5agOwSg==";
      };
    };
    "react-17.0.2" = {
      name = "react";
      packageName = "react";
      version = "17.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-17.0.2.tgz";
        sha512 = "gnhPt75i/dq/z3/6q/0asP78D0u592D5L1pd7M8P+dck6Fu/jJeL6iVVK23fptSUZj8Vjf++7wXA8UNclGQcbA==";
      };
    };
    "react-dom-17.0.2" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "17.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-17.0.2.tgz";
        sha512 = "s4h96KtLDUQlsENhMn1ar8t2bEa+q/YAtj8pPPdIjPDGBDIVNsrD9aXNWqspUe6AzKCIG0C1HZZLqLV7qpOBGA==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "require-from-string-2.0.2" = {
      name = "require-from-string";
      packageName = "require-from-string";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz";
        sha512 = "Xf0nWe6RseziFMu+Ap9biiUbmplq6S9/p+7w7YXP/JBHhrUDDUhwa+vANyubuqfZWTveU//DYVGsDG7RKL/vEw==";
      };
    };
    "resolve-alpn-1.2.1" = {
      name = "resolve-alpn";
      packageName = "resolve-alpn";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-alpn/-/resolve-alpn-1.2.1.tgz";
        sha512 = "0a1F4l73/ZFZOakJnQ3FvkJ2+gSTQWz/r2KE5OdDY0TxPm5h4GkqkWWfM47T7HsbnOtcJVEF4epCVy6u7Q3K+g==";
      };
    };
    "responselike-3.0.0" = {
      name = "responselike";
      packageName = "responselike";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/responselike/-/responselike-3.0.0.tgz";
        sha512 = "40yHxbNcl2+rzXvZuVkrYohathsSJlMTXKryG5y8uciHv1+xDLHQpgjG64JUO9nrEq2jGLH6IZ8BcZyw3wrweg==";
      };
    };
    "ret-0.2.2" = {
      name = "ret";
      packageName = "ret";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ret/-/ret-0.2.2.tgz";
        sha512 = "M0b3YWQs7R3Z917WRQy1HHA7Ba7D8hvZg6UE5mLykJxQVE2ju0IXbGlaHPPlkY+WN7wFP+wUMXmBFA0aV6vYGQ==";
      };
    };
    "reusify-1.0.4" = {
      name = "reusify";
      packageName = "reusify";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/reusify/-/reusify-1.0.4.tgz";
        sha512 = "U9nH88a3fc/ekCF1l0/UP1IosiuIjyTh7hBvXVMHYgVcfGvt897Xguj2UOLDeI5BG2m7/uwyaLVT6fbtCwTyzw==";
      };
    };
    "rfdc-1.3.0" = {
      name = "rfdc";
      packageName = "rfdc";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rfdc/-/rfdc-1.3.0.tgz";
        sha512 = "V2hovdzFbOi77/WajaSMXk2OLm+xNIeQdMMuB7icj7bk6zi2F8GGAxigcnDFpJHbNyNcgyJDiP+8nOrY5cZGrA==";
      };
    };
    "rxjs-7.5.7" = {
      name = "rxjs";
      packageName = "rxjs";
      version = "7.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/rxjs/-/rxjs-7.5.7.tgz";
        sha512 = "z9MzKh/UcOqB3i20H6rtrlaE/CgjLOvheWK/9ILrbhROGTweAi1BaFsTT9FbwZi5Trr1qNRs+MXkhmR06awzQA==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safe-regex2-2.0.0" = {
      name = "safe-regex2";
      packageName = "safe-regex2";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-regex2/-/safe-regex2-2.0.0.tgz";
        sha512 = "PaUSFsUaNNuKwkBijoAPHAK6/eM6VirvyPWlZ7BAQy4D+hCvh4B6lIG+nPdhbFfIbP+gTGBcrdsOaUs0F+ZBOQ==";
      };
    };
    "scheduler-0.20.2" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.20.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.20.2.tgz";
        sha512 = "2eWfGgAqqWFGqtdMmcL5zCMK1U8KlXv8SQFGglL3CEtd0aDVDWgeF/YoCmvln55m5zSk3J/20hTaSBeSObsQDQ==";
      };
    };
    "secure-json-parse-2.5.0" = {
      name = "secure-json-parse";
      packageName = "secure-json-parse";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/secure-json-parse/-/secure-json-parse-2.5.0.tgz";
        sha512 = "ZQruFgZnIWH+WyO9t5rWt4ZEGqCKPwhiw+YbzTwpmT9elgLrLcfuyUiSnwwjUiVy9r4VM3urtbNF1xmEh9IL2w==";
      };
    };
    "semver-7.3.8" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.8.tgz";
        sha512 = "NB1ctGL5rlHrPJtFDVIVzTyQylMLu9N9VICA6HSFJo8MCGVTMW6gfpicwKmmK/dAjTOrqu5l63JJOpDSrAis3A==";
      };
    };
    "semver-store-0.3.0" = {
      name = "semver-store";
      packageName = "semver-store";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver-store/-/semver-store-0.3.0.tgz";
        sha512 = "TcZvGMMy9vodEFSse30lWinkj+JgOBvPn8wRItpQRSayhc+4ssDs335uklkfvQQJgL/WvmHLVj4Ycv2s7QCQMg==";
      };
    };
    "send-0.17.2" = {
      name = "send";
      packageName = "send";
      version = "0.17.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.17.2.tgz";
        sha512 = "UJYB6wFSJE3G00nEivR5rgWp8c2xXvJ3OPWPhmuteU0IKj8nKbG3DrjiOmLwpnHGYWAVwA69zmTm++YG0Hmwww==";
      };
    };
    "set-cookie-parser-2.5.1" = {
      name = "set-cookie-parser";
      packageName = "set-cookie-parser";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-cookie-parser/-/set-cookie-parser-2.5.1.tgz";
        sha512 = "1jeBGaKNGdEq4FgIrORu/N570dwoPYio8lSoYLWmX7sQ//0JY08Xh9o5pBcgmHQ/MbsYp/aZnOe1s1lIsbLprQ==";
      };
    };
    "setprototypeof-1.2.0" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.2.0.tgz";
        sha512 = "E5LDX7Wrp85Kil5bhZv46j8jOeboKq5JMmYM3gVGdGH8xFpPWXUMsNrlODCrkoxMEeNi/XZIwuRvY4XNwYMJpw==";
      };
    };
    "sonic-boom-1.4.1" = {
      name = "sonic-boom";
      packageName = "sonic-boom";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sonic-boom/-/sonic-boom-1.4.1.tgz";
        sha512 = "LRHh/A8tpW7ru89lrlkU4AszXt1dbwSjVWguGrmlxE7tawVmDBlI1PILMkXAxJTwqhgsEeTHzj36D5CmHgQmNg==";
      };
    };
    "statuses-1.5.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.5.0.tgz";
        sha512 = "OpZ3zP+jT1PI7I8nemJX4AKmAX070ZkYPVWV/AaKTJl+tXCTGyVdC1a4SL8RUQYEwk/f34ZX8UTykN68FwrqAA==";
      };
    };
    "string-similarity-4.0.4" = {
      name = "string-similarity";
      packageName = "string-similarity";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-similarity/-/string-similarity-4.0.4.tgz";
        sha512 = "/q/8Q4Bl4ZKAPjj8WerIBJWALKkaPRfrvhfF8k/B23i4nzrlRj2/go1m90In7nG/3XDSbOo0+pu6RvCTM9RGMQ==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "tiny-lru-8.0.2" = {
      name = "tiny-lru";
      packageName = "tiny-lru";
      version = "8.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-lru/-/tiny-lru-8.0.2.tgz";
        sha512 = "ApGvZ6vVvTNdsmt676grvCkUCGwzG9IqXma5Z07xJgiC5L7akUMof5U8G2JTI9Rz/ovtVhJBlY6mNhEvtjzOIg==";
      };
    };
    "toidentifier-1.0.1" = {
      name = "toidentifier";
      packageName = "toidentifier";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/toidentifier/-/toidentifier-1.0.1.tgz";
        sha512 = "o5sSPKEkg/DIQNmH43V0/uerLrpzVedkUh8tGNvaeXpfpuwjKenlSox/2O/BTlZUtEe+JG7s5YhEz608PlAHRA==";
      };
    };
    "tslib-2.4.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.4.1.tgz";
        sha512 = "tGyy4dAjRIEwI7BzsB0lynWgOpfqjUdq91XXAlIWD2OwKBH7oCl/GZG/HT4BOHrTlPMOASlMQ7veyTqpmRcrNA==";
      };
    };
    "uri-js-4.4.1" = {
      name = "uri-js";
      packageName = "uri-js";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-js/-/uri-js-4.4.1.tgz";
        sha512 = "7rKUyy33Q1yc98pQ1DAmLtwX109F7TIfWlW1Ydo8Wl1ii1SeHieeh0HHfPeL2fMXK6z0s8ecKs9frCuLJvndBg==";
      };
    };
    "uri-template-2.0.0" = {
      name = "uri-template";
      packageName = "uri-template";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-template/-/uri-template-2.0.0.tgz";
        sha512 = "r/i44nPoo0ktEZDjx+hxp9PSjQuBBfsd6RgCRuuMqCP0FZEp+YE0SpihThI4UGc5ePqQEFsdyZc7UVlowp+LLw==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
    "xdg-portable-10.5.1" = {
      name = "xdg-portable";
      packageName = "xdg-portable";
      version = "10.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xdg-portable/-/xdg-portable-10.5.1.tgz";
        sha512 = "dKX7yn1jgKqh4GENubRidDpDoaRmwwoiEph2JAcDUD6n3/5ROy5rQo42MX8iIl0UCUhVpsoU2jth5DtdvOATvA==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "yocto-queue-0.1.0" = {
      name = "yocto-queue";
      packageName = "yocto-queue";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yocto-queue/-/yocto-queue-0.1.0.tgz";
        sha512 = "rVksvsnNCdJ/ohGc6xgPwyN8eheCxsiLM8mxuE/t/mOVqJewPuO1miLpTHQiRgTKCLexL4MeAFVagts7HmNZ2Q==";
      };
    };
  };
  args = {
    name = "bbrf-radio";
    packageName = "bbrf-radio";
    version = "0.3.1";
    src = ./.;
    dependencies = [
      sources."@esbuild/linux-loong64-0.14.54"
      sources."@fastify/ajv-compiler-1.1.0"
      sources."@fastify/error-2.0.0"
      sources."@fastify/static-5.0.2"
      sources."@sindresorhus/is-5.3.0"
      sources."@szmarczak/http-timer-5.0.1"
      sources."@types/http-cache-semantics-4.0.1"
      sources."abstract-logging-2.0.1"
      sources."ajv-6.12.6"
      sources."archy-1.0.0"
      sources."atomic-sleep-1.0.0"
      (sources."avvio-7.2.5" // {
        dependencies = [
          sources."debug-4.3.4"
          sources."ms-2.1.2"
        ];
      })
      sources."balanced-match-1.0.2"
      sources."brace-expansion-1.1.11"
      sources."cacheable-lookup-7.0.0"
      sources."cacheable-request-10.2.2"
      sources."concat-map-0.0.1"
      sources."content-disposition-0.5.4"
      sources."cookie-0.5.0"
      (sources."debug-2.6.9" // {
        dependencies = [
          sources."ms-2.0.0"
        ];
      })
      (sources."decompress-response-6.0.0" // {
        dependencies = [
          sources."mimic-response-3.1.0"
        ];
      })
      sources."deepmerge-4.2.2"
      sources."defer-to-connect-2.0.1"
      sources."depd-1.1.2"
      sources."destroy-1.0.4"
      sources."ee-first-1.1.1"
      sources."encodeurl-1.0.2"
      sources."encoding-negotiator-2.0.1"
      sources."esbuild-0.14.54"
      sources."esbuild-android-64-0.14.54"
      sources."esbuild-android-arm64-0.14.54"
      sources."esbuild-darwin-64-0.14.54"
      sources."esbuild-darwin-arm64-0.14.54"
      sources."esbuild-freebsd-64-0.14.54"
      sources."esbuild-freebsd-arm64-0.14.54"
      sources."esbuild-linux-32-0.14.54"
      sources."esbuild-linux-64-0.14.54"
      sources."esbuild-linux-arm-0.14.54"
      sources."esbuild-linux-arm64-0.14.54"
      sources."esbuild-linux-mips64le-0.14.54"
      sources."esbuild-linux-ppc64le-0.14.54"
      sources."esbuild-linux-riscv64-0.14.54"
      sources."esbuild-linux-s390x-0.14.54"
      sources."esbuild-netbsd-64-0.14.54"
      sources."esbuild-openbsd-64-0.14.54"
      sources."esbuild-sunos-64-0.14.54"
      sources."esbuild-windows-32-0.14.54"
      sources."esbuild-windows-64-0.14.54"
      sources."esbuild-windows-arm64-0.14.54"
      sources."escape-html-1.0.3"
      sources."etag-1.8.1"
      sources."fast-decode-uri-component-1.0.1"
      sources."fast-deep-equal-3.1.3"
      sources."fast-json-stable-stringify-2.1.0"
      sources."fast-json-stringify-2.7.13"
      sources."fast-redact-3.1.2"
      sources."fast-safe-stringify-2.1.1"
      sources."fastify-3.29.3"
      sources."fastify-plugin-3.0.1"
      sources."fastq-1.13.0"
      sources."find-my-way-4.5.1"
      sources."flatstr-1.0.12"
      sources."form-data-encoder-2.1.3"
      sources."forwarded-0.2.0"
      sources."fresh-0.5.2"
      sources."fs.realpath-1.0.0"
      sources."fsevents-2.3.2"
      sources."get-stream-6.0.1"
      sources."glob-7.2.3"
      sources."got-12.5.3"
      sources."http-cache-semantics-4.1.0"
      sources."http-errors-1.8.1"
      sources."http2-wrapper-2.2.0"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."ipaddr.js-1.9.1"
      sources."js-tokens-4.0.0"
      sources."json-buffer-3.0.1"
      sources."json-schema-traverse-0.4.1"
      sources."keyv-4.5.2"
      (sources."light-my-request-4.12.0" // {
        dependencies = [
          sources."ajv-8.11.2"
          sources."json-schema-traverse-1.0.0"
        ];
      })
      sources."loose-envify-1.4.0"
      sources."lowercase-keys-3.0.0"
      sources."lru-cache-6.0.0"
      sources."mime-1.6.0"
      sources."mimic-response-4.0.0"
      sources."minimatch-3.1.2"
      sources."ms-2.1.3"
      sources."normalize-url-7.2.0"
      sources."object-assign-4.1.1"
      sources."on-finished-2.3.0"
      sources."once-1.4.0"
      sources."os-paths-7.3.0"
      sources."p-cancelable-3.0.0"
      sources."p-limit-3.1.0"
      sources."path-is-absolute-1.0.1"
      sources."pct-encode-1.0.2"
      sources."pino-6.14.0"
      sources."pino-std-serializers-3.2.0"
      sources."process-warning-1.0.0"
      sources."proxy-addr-2.0.7"
      sources."punycode-2.1.1"
      sources."queue-microtask-1.2.3"
      sources."quick-format-unescaped-4.0.4"
      sources."quick-lru-5.1.1"
      sources."ramda-0.28.0"
      sources."range-parser-1.2.1"
      sources."react-17.0.2"
      sources."react-dom-17.0.2"
      sources."readable-stream-3.6.0"
      sources."require-from-string-2.0.2"
      sources."resolve-alpn-1.2.1"
      sources."responselike-3.0.0"
      sources."ret-0.2.2"
      sources."reusify-1.0.4"
      sources."rfdc-1.3.0"
      sources."rxjs-7.5.7"
      sources."safe-buffer-5.2.1"
      sources."safe-regex2-2.0.0"
      sources."scheduler-0.20.2"
      sources."secure-json-parse-2.5.0"
      sources."semver-7.3.8"
      sources."semver-store-0.3.0"
      sources."send-0.17.2"
      sources."set-cookie-parser-2.5.1"
      sources."setprototypeof-1.2.0"
      sources."sonic-boom-1.4.1"
      sources."statuses-1.5.0"
      sources."string-similarity-4.0.4"
      sources."string_decoder-1.3.0"
      sources."tiny-lru-8.0.2"
      sources."toidentifier-1.0.1"
      sources."tslib-2.4.1"
      sources."uri-js-4.4.1"
      sources."uri-template-2.0.0"
      sources."util-deprecate-1.0.2"
      sources."wrappy-1.0.2"
      sources."xdg-portable-10.5.1"
      sources."yallist-4.0.0"
      sources."yocto-queue-0.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      license = "GPL-2.0-only";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ]
        args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
