# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@esbuild/android-arm-0.18.8" = {
      name = "_at_esbuild_slash_android-arm";
      packageName = "@esbuild/android-arm";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/android-arm/-/android-arm-0.18.8.tgz";
        sha512 = "xDncukyW2b/JU04AZJ6cSAp4FaoAMyxFFTgmmNEKbjn2MwThw/ekHwt3d84Nm0fJG2KqKBS3D6uGDo2jzDN/uQ==";
      };
    };
    "@esbuild/android-arm64-0.18.8" = {
      name = "_at_esbuild_slash_android-arm64";
      packageName = "@esbuild/android-arm64";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/android-arm64/-/android-arm64-0.18.8.tgz";
        sha512 = "8N8gkGu8vBq/cRPs8DDQmdwmS097A+XRHC/ay6wJjSEdLV3onTnfIkzew+g86k5bcakbxsE7zynCIhG0IgCT5Q==";
      };
    };
    "@esbuild/android-x64-0.18.8" = {
      name = "_at_esbuild_slash_android-x64";
      packageName = "@esbuild/android-x64";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/android-x64/-/android-x64-0.18.8.tgz";
        sha512 = "vLTz/naWZMVY01T0B6gneUmm9RTYBlhRzjSCDuQCZURC1Lp3Fw2gP32ZFTtIaMBK+hfSJilnmgTPuUkCTH6CwA==";
      };
    };
    "@esbuild/darwin-arm64-0.18.8" = {
      name = "_at_esbuild_slash_darwin-arm64";
      packageName = "@esbuild/darwin-arm64";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/darwin-arm64/-/darwin-arm64-0.18.8.tgz";
        sha512 = "14oQ5IgillH6K7j750ug0IUfy86ql1CrHx4uxRMlq0lH5NthxEH+QIgqIzUUyDJdw0lOodtr4L905Q9VYIG2+g==";
      };
    };
    "@esbuild/darwin-x64-0.18.8" = {
      name = "_at_esbuild_slash_darwin-x64";
      packageName = "@esbuild/darwin-x64";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/darwin-x64/-/darwin-x64-0.18.8.tgz";
        sha512 = "OyEf+21R32glxR+IJpPhBgcbxSbc7adPe4hYggu2mbjqAAjJJAaYoYjNeojyp+ZKY2ZRX3FimBbeExVoPdEDfg==";
      };
    };
    "@esbuild/freebsd-arm64-0.18.8" = {
      name = "_at_esbuild_slash_freebsd-arm64";
      packageName = "@esbuild/freebsd-arm64";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/freebsd-arm64/-/freebsd-arm64-0.18.8.tgz";
        sha512 = "ur5cFSmlE5YPqD+5X9E32wJ2nBnz/Lk30QuAiotam0kx2e2f9+dgTarqaDhUKt+xJo+6OLhCpHAlogQ1TAvJrw==";
      };
    };
    "@esbuild/freebsd-x64-0.18.8" = {
      name = "_at_esbuild_slash_freebsd-x64";
      packageName = "@esbuild/freebsd-x64";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/freebsd-x64/-/freebsd-x64-0.18.8.tgz";
        sha512 = "j0dgVXUyInggnvEgFGS7FXTQncRwAmHkgAy8YE52kOsozkimpapE3Kuuwb6MXbhnqLvJevaFgGSAlseDlkXAlg==";
      };
    };
    "@esbuild/linux-arm-0.18.8" = {
      name = "_at_esbuild_slash_linux-arm";
      packageName = "@esbuild/linux-arm";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/linux-arm/-/linux-arm-0.18.8.tgz";
        sha512 = "moCWasFnLWfVmZjux2wE1YRoJlQ36hlthVD/B+UTic3UgCZ5LvpHTeqnF037JL9zS1W6d+cB0hUwithdIyZ/1w==";
      };
    };
    "@esbuild/linux-arm64-0.18.8" = {
      name = "_at_esbuild_slash_linux-arm64";
      packageName = "@esbuild/linux-arm64";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/linux-arm64/-/linux-arm64-0.18.8.tgz";
        sha512 = "Xp8brdqVVSTiN3/GGEAkMN1V2VCUrt11lxqHopYsbAvIf2YAfaW02/NFlekMq7SaAVcReYqbO7LReaOLzHaxgw==";
      };
    };
    "@esbuild/linux-ia32-0.18.8" = {
      name = "_at_esbuild_slash_linux-ia32";
      packageName = "@esbuild/linux-ia32";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/linux-ia32/-/linux-ia32-0.18.8.tgz";
        sha512 = "mUDNdkY8mr4kZrekGLwZBFpvVX1VJLpwYUsbKTM/w0h4xVgsupc440nlsUfyz8OKeE92ZdMUUG8wrdOeZaONiQ==";
      };
    };
    "@esbuild/linux-loong64-0.18.8" = {
      name = "_at_esbuild_slash_linux-loong64";
      packageName = "@esbuild/linux-loong64";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/linux-loong64/-/linux-loong64-0.18.8.tgz";
        sha512 = "wuzn8pABeFielmccZjn44eyVFo9G5rThVT91QdxZ02H7Yxek623ODpZoauAWwdBDFfK1R25RtKkxCvzfeJ1akg==";
      };
    };
    "@esbuild/linux-mips64el-0.18.8" = {
      name = "_at_esbuild_slash_linux-mips64el";
      packageName = "@esbuild/linux-mips64el";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/linux-mips64el/-/linux-mips64el-0.18.8.tgz";
        sha512 = "9vIq+bR1PYqTV0Ea38a9h/r2xAecC56eQemOBXyzM3jQ9Bo8f3Q9On7mpiDrXich1eQuo9nna0ZBcaIJxaO58g==";
      };
    };
    "@esbuild/linux-ppc64-0.18.8" = {
      name = "_at_esbuild_slash_linux-ppc64";
      packageName = "@esbuild/linux-ppc64";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/linux-ppc64/-/linux-ppc64-0.18.8.tgz";
        sha512 = "9AFk6CgYytoQ0/RMnmr1zlpTA88g9ksxk0gmo9apY+O8Yzmcjd+Dl9LUX9k89dLnyyLgkHl6uLg1tpEzpQS+yA==";
      };
    };
    "@esbuild/linux-riscv64-0.18.8" = {
      name = "_at_esbuild_slash_linux-riscv64";
      packageName = "@esbuild/linux-riscv64";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/linux-riscv64/-/linux-riscv64-0.18.8.tgz";
        sha512 = "AyuhgbWMSbYrgr3Qz8OT6C92PSbSh7X9ckSgz4xnZYUWrBkR6YaRTp5L7zgcouA/cSm1AiOQauHgQb+EOCNBVQ==";
      };
    };
    "@esbuild/linux-s390x-0.18.8" = {
      name = "_at_esbuild_slash_linux-s390x";
      packageName = "@esbuild/linux-s390x";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/linux-s390x/-/linux-s390x-0.18.8.tgz";
        sha512 = "XU3UTgyFx80B+kCD82kun9usGT1+3YILtGeGx+StNWGT8wjHYCc5ZTsh4g+58kDoGPezquGO+Kso5VSlX2GU2g==";
      };
    };
    "@esbuild/linux-x64-0.18.8" = {
      name = "_at_esbuild_slash_linux-x64";
      packageName = "@esbuild/linux-x64";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/linux-x64/-/linux-x64-0.18.8.tgz";
        sha512 = "/zBMV9cAFYFVTiyf7zg4ubMSfH0BGn5IPD+XZT0m2cYhtlMQLRQlNDpkaz5UlAIZBnBTCpjsbnI8X73xP2Zgtw==";
      };
    };
    "@esbuild/netbsd-x64-0.18.8" = {
      name = "_at_esbuild_slash_netbsd-x64";
      packageName = "@esbuild/netbsd-x64";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/netbsd-x64/-/netbsd-x64-0.18.8.tgz";
        sha512 = "/Aqh6SoP6UpLrgdfgFzi1Von4D5OhnJEYZNdkZA0AREuwSBcZh6X5eUsSCiEszJaeOt/oOZOvSwNR7i2VjmDnA==";
      };
    };
    "@esbuild/openbsd-x64-0.18.8" = {
      name = "_at_esbuild_slash_openbsd-x64";
      packageName = "@esbuild/openbsd-x64";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/openbsd-x64/-/openbsd-x64-0.18.8.tgz";
        sha512 = "twRW7IQ4ar1BilPDFf/IpsQY77dU50IUKZxs7veZVo4rnQbOXw6FPl2rWVJcVx+I6dkGzmt/yM6YW6FBdqA3DA==";
      };
    };
    "@esbuild/sunos-x64-0.18.8" = {
      name = "_at_esbuild_slash_sunos-x64";
      packageName = "@esbuild/sunos-x64";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/sunos-x64/-/sunos-x64-0.18.8.tgz";
        sha512 = "DSgYAFzvRisJQPxtTsUTFJ/Kr1KYZxxrKGfHPMnW2f/0KxOdLwRKbzWeG8g15gSBcDuDCZXnuUSFyu3ZyqbCzA==";
      };
    };
    "@esbuild/win32-arm64-0.18.8" = {
      name = "_at_esbuild_slash_win32-arm64";
      packageName = "@esbuild/win32-arm64";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/win32-arm64/-/win32-arm64-0.18.8.tgz";
        sha512 = "eWoYo48Hp1yWbe2SSnmMNqnVprNgKtp0mP+aUeX/Lkw3gcsgRju5Qj7psfpA8cR0ULeWkrhmaSS4mgj4wfo97A==";
      };
    };
    "@esbuild/win32-ia32-0.18.8" = {
      name = "_at_esbuild_slash_win32-ia32";
      packageName = "@esbuild/win32-ia32";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/win32-ia32/-/win32-ia32-0.18.8.tgz";
        sha512 = "A5mph1zmf7eEbAKZYqRHUBkO5PRdSO0bjH4XMAnYCXfndk72uHzvMmTNS5ZZ1dVUb55P45MFBBlZyW7SsnXxXw==";
      };
    };
    "@esbuild/win32-x64-0.18.8" = {
      name = "_at_esbuild_slash_win32-x64";
      packageName = "@esbuild/win32-x64";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/win32-x64/-/win32-x64-0.18.8.tgz";
        sha512 = "/NKlWmdR5oxLswW/pdMKF8qwwtC7zpeTWvWffXpqNZ4Nib6lmnU2L5ijfSvWy8vxWhwmfR/CXA7GzuRL5nRxow==";
      };
    };
    "@fastify/accept-negotiator-1.1.0" = {
      name = "_at_fastify_slash_accept-negotiator";
      packageName = "@fastify/accept-negotiator";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fastify/accept-negotiator/-/accept-negotiator-1.1.0.tgz";
        sha512 = "OIHZrb2ImZ7XG85HXOONLcJWGosv7sIvM2ifAPQVhg9Lv7qdmMBNVaai4QTdyuaqbKM5eO6sLSQOYI7wEQeCJQ==";
      };
    };
    "@fastify/ajv-compiler-3.5.0" = {
      name = "_at_fastify_slash_ajv-compiler";
      packageName = "@fastify/ajv-compiler";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fastify/ajv-compiler/-/ajv-compiler-3.5.0.tgz";
        sha512 = "ebbEtlI7dxXF5ziNdr05mOY8NnDiPB1XvAlLHctRt/Rc+C3LCOVW5imUVX+mhvUhnNzmPBHewUkOFgGlCxgdAA==";
      };
    };
    "@fastify/deepmerge-1.3.0" = {
      name = "_at_fastify_slash_deepmerge";
      packageName = "@fastify/deepmerge";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fastify/deepmerge/-/deepmerge-1.3.0.tgz";
        sha512 = "J8TOSBq3SoZbDhM9+R/u77hP93gz/rajSA+K2kGyijPpORPWUXHUpTaleoj+92As0S9uPRP7Oi8IqMf0u+ro6A==";
      };
    };
    "@fastify/error-3.4.1" = {
      name = "_at_fastify_slash_error";
      packageName = "@fastify/error";
      version = "3.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fastify/error/-/error-3.4.1.tgz";
        sha512 = "wWSvph+29GR783IhmvdwWnN4bUxTD01Vm5Xad4i7i1VuAOItLvbPAb69sb0IQ2N57yprvhNIwAP5B6xfKTmjmQ==";
      };
    };
    "@fastify/fast-json-stringify-compiler-4.3.0" = {
      name = "_at_fastify_slash_fast-json-stringify-compiler";
      packageName = "@fastify/fast-json-stringify-compiler";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fastify/fast-json-stringify-compiler/-/fast-json-stringify-compiler-4.3.0.tgz";
        sha512 = "aZAXGYo6m22Fk1zZzEUKBvut/CIIQe/BapEORnxiD5Qr0kPHqqI69NtEMCme74h+at72sPhbkb4ZrLd1W3KRLA==";
      };
    };
    "@fastify/send-2.1.0" = {
      name = "_at_fastify_slash_send";
      packageName = "@fastify/send";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fastify/send/-/send-2.1.0.tgz";
        sha512 = "yNYiY6sDkexoJR0D8IDy3aRP3+L4wdqCpvx5WP+VtEU58sn7USmKynBzDQex5X42Zzvw2gNzzYgP90UfWShLFA==";
      };
    };
    "@fastify/static-7.0.0" = {
      name = "_at_fastify_slash_static";
      packageName = "@fastify/static";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fastify/static/-/static-7.0.0.tgz";
        sha512 = "JCuzYMgbIY1Ws5e3dmPFWAZ0MwkKNn4Pmd/gk3RlCOCLDtA6eUq7WZyBz/TpnCi6ae8FOY1s33POo4rioYgWTg==";
      };
    };
    "@isaacs/cliui-8.0.2" = {
      name = "_at_isaacs_slash_cliui";
      packageName = "@isaacs/cliui";
      version = "8.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@isaacs/cliui/-/cliui-8.0.2.tgz";
        sha512 = "O8jcjabXaleOG9DQ0+ARXWZBTfnP4WNAqzuiJK7ll44AmxGKv/J2M4TPjxjY3znBCfvBXFzucm1twdyFybFqEA==";
      };
    };
    "@lukeed/ms-2.0.2" = {
      name = "_at_lukeed_slash_ms";
      packageName = "@lukeed/ms";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@lukeed/ms/-/ms-2.0.2.tgz";
        sha512 = "9I2Zn6+NJLfaGoz9jN3lpwDgAYvfGeNYdbAIjJOqzs4Tpc+VU3Jqq4IofSUBKajiDS8k9fZIg18/z13mpk1bsA==";
      };
    };
    "@pkgjs/parseargs-0.11.0" = {
      name = "_at_pkgjs_slash_parseargs";
      packageName = "@pkgjs/parseargs";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@pkgjs/parseargs/-/parseargs-0.11.0.tgz";
        sha512 = "+1VkjdD0QBLPodGrJUeqarH8VAIvQODIbwh9XpP5Syisf7YoQgsJKPNFoqqLQlu+VQ/tVSshMR6loPMn8U+dPg==";
      };
    };
    "@sindresorhus/is-5.6.0" = {
      name = "_at_sindresorhus_slash_is";
      packageName = "@sindresorhus/is";
      version = "5.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sindresorhus/is/-/is-5.6.0.tgz";
        sha512 = "TV7t8GKYaJWsn00tFDqBw8+Uqmr8A0fRU1tvTQhyZzGv0sJCGRQL3JGMI3ucuKo3XIZdUP+Lx7/gh2t3lewy7g==";
      };
    };
    "@szmarczak/http-timer-5.0.1" = {
      name = "_at_szmarczak_slash_http-timer";
      packageName = "@szmarczak/http-timer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@szmarczak/http-timer/-/http-timer-5.0.1.tgz";
        sha512 = "+PmQX0PiAYPMeVYe237LJAYvOMYW1j2rH5YROyS3b4CTVJum34HfRvKvAzozHAQG0TnHNdUfY9nCeUyRAs//cw==";
      };
    };
    "@types/http-cache-semantics-4.0.4" = {
      name = "_at_types_slash_http-cache-semantics";
      packageName = "@types/http-cache-semantics";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/http-cache-semantics/-/http-cache-semantics-4.0.4.tgz";
        sha512 = "1m0bIFVc7eJWyve9S0RnuRgcQqF/Xd5QsUZAZeQFr1Q3/p9JWoQQEqmVy+DPTNpGXwhgIetAoYF8JSc33q29QA==";
      };
    };
    "abort-controller-3.0.0" = {
      name = "abort-controller";
      packageName = "abort-controller";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/abort-controller/-/abort-controller-3.0.0.tgz";
        sha512 = "h8lQ8tacZYnR3vNQTgibj+tODHI5/+l06Au2Pcriv/Gmet0eaj4TwWH41sO9wnHDiQsEj19q0drzdWdeAHtweg==";
      };
    };
    "abstract-logging-2.0.1" = {
      name = "abstract-logging";
      packageName = "abstract-logging";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abstract-logging/-/abstract-logging-2.0.1.tgz";
        sha512 = "2BjRTZxTPvheOvGbBslFSYOUkr+SjPtOnrLP33f+VIWLzezQpZcqVg7ja3L4dBXmzzgwT+a029jRx5PCi3JuiA==";
      };
    };
    "ajv-8.12.0" = {
      name = "ajv";
      packageName = "ajv";
      version = "8.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-8.12.0.tgz";
        sha512 = "sRu1kpcO9yLtYxBKvqfTeh9KzZEwO3STyX1HT+4CaDzC6HpTGYhIhPIzj9XuKU7KYDwnaeh5hcOwjy1QuJzBPA==";
      };
    };
    "ajv-formats-2.1.1" = {
      name = "ajv-formats";
      packageName = "ajv-formats";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv-formats/-/ajv-formats-2.1.1.tgz";
        sha512 = "Wx0Kx52hxE7C18hkMEggYlEifqWZtYaRgouJor+WMdPnQyEK13vgEWyVNup7SoeeoLMsr4kf5h6dOW11I15MUA==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-regex-6.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-6.0.1.tgz";
        sha512 = "n5M855fKb2SsfMIiFFoVrABHJC8QtHwVx+mHWP3QcEqBHYienj5dHSgjbxtC0WEZXYt4wcD6zrQElDPhFuZgfA==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "ansi-styles-6.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-6.2.1.tgz";
        sha512 = "bN798gFfQX+viw3R7yrGWRqnrN2oRkEkUjjl4JNn4E8GxxbjtG3FbrEIIY3l8/hrwUwIeCZvi4QuOTP4MErVug==";
      };
    };
    "archy-1.0.0" = {
      name = "archy";
      packageName = "archy";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/archy/-/archy-1.0.0.tgz";
        sha512 = "Xg+9RwCg/0p32teKdGMPTPnVXKD0w3DfHnFTficozsAgsvq2XenPJq/MYpzzQ/v8zrOyJn6Ds39VA4JIDwFfqw==";
      };
    };
    "atomic-sleep-1.0.0" = {
      name = "atomic-sleep";
      packageName = "atomic-sleep";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/atomic-sleep/-/atomic-sleep-1.0.0.tgz";
        sha512 = "kNOjDqAh7px0XWNI+4QbzoiR/nTkHAWNud2uvnJquD1/x5a7EQZMJT0AczqK0Qn67oY/TTQ1LbUKajZpp3I9tQ==";
      };
    };
    "avvio-8.2.1" = {
      name = "avvio";
      packageName = "avvio";
      version = "8.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/avvio/-/avvio-8.2.1.tgz";
        sha512 = "TAlMYvOuwGyLK3PfBb5WKBXZmXz2fVCgv23d6zZFdle/q3gPjmxBaeuC0pY0Dzs5PWMSgfqqEZkrye19GlDTgw==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "base64-js-1.5.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
        sha512 = "AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
      };
    };
    "brace-expansion-2.0.1" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-2.0.1.tgz";
        sha512 = "XnAIvQ8eM+kC6aULx6wuQiwVsnzsi9d3WxzV3FpWTGA19F621kwdbsAcFKXgKUHZWsy+mY6iL1sHTxWEFCytDA==";
      };
    };
    "buffer-6.0.3" = {
      name = "buffer";
      packageName = "buffer";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-6.0.3.tgz";
        sha512 = "FTiCpNxtwiZZHEZbcbTIcZjERVICn9yq/pDFkTl95/AxzD1naBctN7YO68riM/gLSDY7sdrMby8hofADYuuqOA==";
      };
    };
    "cacheable-lookup-7.0.0" = {
      name = "cacheable-lookup";
      packageName = "cacheable-lookup";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cacheable-lookup/-/cacheable-lookup-7.0.0.tgz";
        sha512 = "+qJyx4xiKra8mZrcwhjMRMUhD5NR1R8esPkzIYxX96JiecFoxAXFuz/GpR3+ev4PE1WamHip78wV0vcmPQtp8w==";
      };
    };
    "cacheable-request-10.2.14" = {
      name = "cacheable-request";
      packageName = "cacheable-request";
      version = "10.2.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/cacheable-request/-/cacheable-request-10.2.14.tgz";
        sha512 = "zkDT5WAF4hSSoUgyfg5tFIxz8XQK+25W/TLVojJTMKBaxevLBBtLxgqguAuVQB8PVW79FVjHcU+GJ9tVbDZ9mQ==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "content-disposition-0.5.4" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.4.tgz";
        sha512 = "FveZTNuGw04cxlAiWbzi6zTAL/lhehaWbTtgluJh4/E95DqMwTmha3KZN1aAWA8cFIhHzMZUvLevkw5Rqk+tSQ==";
      };
    };
    "cookie-0.5.0" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.5.0.tgz";
        sha512 = "YZ3GUyn/o8gfKJlnlX7g7xq4gyO6OSuhGPKaaGssGB2qgDUS0gPgtTvoyZLTt9Ab6dC4hfc9dV5arkvc/OCmrw==";
      };
    };
    "cross-spawn-7.0.3" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "7.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.3.tgz";
        sha512 = "iRDPJKUPVEND7dHPO8rkbOnPpyDygcDFtWjpeWNCgy8WP2rXcxXL8TskReQl6OrB2G7+UJrags1q15Fudc7G6w==";
      };
    };
    "debug-4.3.4" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz";
        sha512 = "PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==";
      };
    };
    "decompress-response-6.0.0" = {
      name = "decompress-response";
      packageName = "decompress-response";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-response/-/decompress-response-6.0.0.tgz";
        sha512 = "aW35yZM6Bb/4oJlZncMH2LCoZtJXTRxES17vE3hoRiowU2kWHaJKFkSBDnDR+cm9J+9QhXmREyIfv0pji9ejCQ==";
      };
    };
    "defer-to-connect-2.0.1" = {
      name = "defer-to-connect";
      packageName = "defer-to-connect";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/defer-to-connect/-/defer-to-connect-2.0.1.tgz";
        sha512 = "4tvttepXG1VaYGrRibk5EwJd1t4udunSOVMdLSAL6mId1ix438oPwPZMALY41FCijukO1L0twNcGsdzS7dHgDg==";
      };
    };
    "depd-2.0.0" = {
      name = "depd";
      packageName = "depd";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-2.0.0.tgz";
        sha512 = "g7nH6P6dyDioJogAAGprGpCtVImJhpPk/roCzdb3fIh61/s/nPsfR6onyMwkCAR/OlC3yBC0lESvUoQEAssIrw==";
      };
    };
    "eastasianwidth-0.2.0" = {
      name = "eastasianwidth";
      packageName = "eastasianwidth";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eastasianwidth/-/eastasianwidth-0.2.0.tgz";
        sha512 = "I88TYZWc9XiYHRQ4/3c5rjjfgkjhLyW2luGIheGERbNQ6OY7yTybanSpDXZa8y7VUP9YmDcYa+eyq4ca7iLqWA==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "emoji-regex-9.2.2" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "9.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-9.2.2.tgz";
        sha512 = "L18DaJsXSUk2+42pv8mLs5jJT2hqFkFE4j21wOmgbUqsZ2hL72NsUU785g9RXgo3s0ZNgVl42TiHp3ZtOv/Vyg==";
      };
    };
    "esbuild-0.18.8" = {
      name = "esbuild";
      packageName = "esbuild";
      version = "0.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild/-/esbuild-0.18.8.tgz";
        sha512 = "3hJ4I81Wp1IT5z29FAlTAlbX+ElIqy4AuIf1GNcFjsRIfyO3linxmEVqoP865KTYT9BWosrCl081RM/35Z+scw==";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha512 = "NiSupZ4OeuGwr68lGIeym/ksIZMJodUGOSCZ/FSnTxcrekbvqrgdUxlJOMpijaKZVjAJrWrGs/6Jy8OMuyj9ow==";
      };
    };
    "event-target-shim-5.0.1" = {
      name = "event-target-shim";
      packageName = "event-target-shim";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-target-shim/-/event-target-shim-5.0.1.tgz";
        sha512 = "i/2XbnSz/uxRCU6+NdVJgKWDTM427+MqYbkQzD321DuCQJUqOuJKIA0IM2+W2xtYHdKOmZ4dR6fExsd4SXL+WQ==";
      };
    };
    "events-3.3.0" = {
      name = "events";
      packageName = "events";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/events/-/events-3.3.0.tgz";
        sha512 = "mQw+2fkQbALzQ7V0MY0IqdnXNOeTtP4r0lN9z7AAawCXgqea7bDii20AYrIBrFd/Hx0M2Ocz6S111CaFkUcb0Q==";
      };
    };
    "fast-content-type-parse-1.1.0" = {
      name = "fast-content-type-parse";
      packageName = "fast-content-type-parse";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-content-type-parse/-/fast-content-type-parse-1.1.0.tgz";
        sha512 = "fBHHqSTFLVnR61C+gltJuE5GkVQMV0S2nqUO8TJ+5Z3qAKG8vAx4FKai1s5jq/inV1+sREynIWSuQ6HgoSXpDQ==";
      };
    };
    "fast-decode-uri-component-1.0.1" = {
      name = "fast-decode-uri-component";
      packageName = "fast-decode-uri-component";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-decode-uri-component/-/fast-decode-uri-component-1.0.1.tgz";
        sha512 = "WKgKWg5eUxvRZGwW8FvfbaH7AXSh2cL+3j5fMGzUMCxWBJ3dV3a7Wz8y2f/uQ0e3B6WmodD3oS54jTQ9HVTIIg==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fast-json-stringify-5.11.1" = {
      name = "fast-json-stringify";
      packageName = "fast-json-stringify";
      version = "5.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stringify/-/fast-json-stringify-5.11.1.tgz";
        sha512 = "Lrj3tmc/qI1OCmr0WJEJFC4TxnAdLnbZZ0CvFvHv/PHNieLCX12PNBlV9KGIDS08w49T8h7vkMuzNoB+3NyX0g==";
      };
    };
    "fast-querystring-1.1.2" = {
      name = "fast-querystring";
      packageName = "fast-querystring";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-querystring/-/fast-querystring-1.1.2.tgz";
        sha512 = "g6KuKWmFXc0fID8WWH0jit4g0AGBoJhCkJMb1RmbsSEUNvQ+ZC8D6CUZ+GtF8nMzSPXnhiePyyqqipzNNEnHjg==";
      };
    };
    "fast-redact-3.3.0" = {
      name = "fast-redact";
      packageName = "fast-redact";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-redact/-/fast-redact-3.3.0.tgz";
        sha512 = "6T5V1QK1u4oF+ATxs1lWUmlEk6P2T9HqJG3e2DnHOdVgZy2rFJBoEnrIedcTXlkAHU/zKC+7KETJ+KGGKwxgMQ==";
      };
    };
    "fast-uri-2.3.0" = {
      name = "fast-uri";
      packageName = "fast-uri";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-uri/-/fast-uri-2.3.0.tgz";
        sha512 = "eel5UKGn369gGEWOqBShmFJWfq/xSJvsgDzgLYC845GneayWvXBf0lJCBn5qTABfewy1ZDPoaR5OZCP+kssfuw==";
      };
    };
    "fastify-4.26.0" = {
      name = "fastify";
      packageName = "fastify";
      version = "4.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastify/-/fastify-4.26.0.tgz";
        sha512 = "Fq/7ziWKc6pYLYLIlCRaqJqEVTIZ5tZYfcW/mDK2AQ9v/sqjGFpj0On0/7hU50kbPVjLO4de+larPA1WwPZSfw==";
      };
    };
    "fastify-plugin-4.5.1" = {
      name = "fastify-plugin";
      packageName = "fastify-plugin";
      version = "4.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastify-plugin/-/fastify-plugin-4.5.1.tgz";
        sha512 = "stRHYGeuqpEZTL1Ef0Ovr2ltazUT9g844X5z/zEBFLG8RYlpDiOCIG+ATvYEp+/zmc7sN29mcIMp8gvYplYPIQ==";
      };
    };
    "fastq-1.17.0" = {
      name = "fastq";
      packageName = "fastq";
      version = "1.17.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastq/-/fastq-1.17.0.tgz";
        sha512 = "zGygtijUMT7jnk3h26kUms3BkSDp4IfIKjmnqI2tvx6nuBfiF1UqOxbnLfzdv+apBy+53oaImsKtMw/xYbW+1w==";
      };
    };
    "find-my-way-8.1.0" = {
      name = "find-my-way";
      packageName = "find-my-way";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-my-way/-/find-my-way-8.1.0.tgz";
        sha512 = "41QwjCGcVTODUmLLqTMeoHeiozbMXYMAE1CKFiDyi9zVZ2Vjh0yz3MF0WQZoIb+cmzP/XlbFjlF2NtJmvZHznA==";
      };
    };
    "foreground-child-3.1.1" = {
      name = "foreground-child";
      packageName = "foreground-child";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/foreground-child/-/foreground-child-3.1.1.tgz";
        sha512 = "TMKDUnIte6bfb5nWv7V/caI169OHgvwjb7V4WkeUvbQQdjr5rWKqHFiKWb/fcOwB+CzBT+qbWjvj+DVwRskpIg==";
      };
    };
    "form-data-encoder-2.1.4" = {
      name = "form-data-encoder";
      packageName = "form-data-encoder";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data-encoder/-/form-data-encoder-2.1.4.tgz";
        sha512 = "yDYSgNMraqvnxiEXO4hi88+YZxaHC6QKzb5N84iRCTDeRO7ZALpir/lVmf/uXUhnwUr2O4HU8s/n6x+yNjQkHw==";
      };
    };
    "forwarded-0.2.0" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.2.0.tgz";
        sha512 = "buRG0fpBtRHSTCOASe6hD258tEubFoRLb4ZNA6NxMVHNw2gOcwHo9wyablzMzOA5z9xA9L1KNjk/Nt6MT9aYow==";
      };
    };
    "get-stream-6.0.1" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-6.0.1.tgz";
        sha512 = "ts6Wi+2j3jQjqi70w5AlN8DFnkSwC+MqmxEzdEALB2qXZYV3X/b1CTfgPLGJNMeAWxdPfU8FO1ms3NUfaHCPYg==";
      };
    };
    "glob-10.3.10" = {
      name = "glob";
      packageName = "glob";
      version = "10.3.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-10.3.10.tgz";
        sha512 = "fa46+tv1Ak0UPK1TOy/pZrIybNNt4HCv7SDzwyfiOZkvZLEbjsZkJBPtDHVshZjbecAoAGSC20MjLDG/qr679g==";
      };
    };
    "got-12.6.1" = {
      name = "got";
      packageName = "got";
      version = "12.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/got/-/got-12.6.1.tgz";
        sha512 = "mThBblvlAF1d4O5oqyvN+ZxLAYwIJK7bpMxgYqPD9okW0C3qm5FFn7k811QrcuEBwaogR3ngOFoCfs6mRv7teQ==";
      };
    };
    "http-cache-semantics-4.1.1" = {
      name = "http-cache-semantics";
      packageName = "http-cache-semantics";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-cache-semantics/-/http-cache-semantics-4.1.1.tgz";
        sha512 = "er295DKPVsV82j5kw1Gjt+ADA/XYHsajl82cGNQG2eyoPkvgUhX+nDIyelzhIWbbsXP39EHcI6l5tYs2FYqYXQ==";
      };
    };
    "http-errors-2.0.0" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-2.0.0.tgz";
        sha512 = "FtwrG/euBzaEjYeRqOgly7G0qviiXoJWnvEH2Z1plBdXgbyjv34pHTSb9zoeHMyDy33+DWy5Wt9Wo+TURtOYSQ==";
      };
    };
    "http2-wrapper-2.1.11" = {
      name = "http2-wrapper";
      packageName = "http2-wrapper";
      version = "2.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/http2-wrapper/-/http2-wrapper-2.1.11.tgz";
        sha512 = "aNAk5JzLturWEUiuhAN73Jcbq96R7rTitAoXV54FYMatvihnpD2+6PUgU4ce3D/m5VDbw+F5CsyKSF176ptitQ==";
      };
    };
    "ieee754-1.2.1" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
        sha512 = "dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ipaddr.js-1.9.1" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.9.1.tgz";
        sha512 = "0KI/607xoxSToH7GjN1FfSbLoU0+btTicjsQSWQlh/hZykN8KpmMf7uYwPW3R+akZ6R/w18ZlXSHBYXiYUPO3g==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "jackspeak-2.3.6" = {
      name = "jackspeak";
      packageName = "jackspeak";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/jackspeak/-/jackspeak-2.3.6.tgz";
        sha512 = "N3yCS/NegsOBokc8GAdM8UcmfsKiSS8cipheD/nivzr700H+nsMOxJjQnvwOcRYVuFkdH0wGUvW2WbXGmrZGbQ==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "json-buffer-3.0.1" = {
      name = "json-buffer";
      packageName = "json-buffer";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-buffer/-/json-buffer-3.0.1.tgz";
        sha512 = "4bV5BfR2mqfQTJm+V5tPPdf+ZpuhiIvTuAB5g8kcrXOZpTT/QwwVRWBywX1ozr6lEuPdbHxwaJlm9G6mI2sfSQ==";
      };
    };
    "json-schema-ref-resolver-1.0.1" = {
      name = "json-schema-ref-resolver";
      packageName = "json-schema-ref-resolver";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-ref-resolver/-/json-schema-ref-resolver-1.0.1.tgz";
        sha512 = "EJAj1pgHc1hxF6vo2Z3s69fMjO1INq6eGHXZ8Z6wCQeldCuwxGK9Sxf4/cScGn3FZubCVUehfWtcDM/PLteCQw==";
      };
    };
    "json-schema-traverse-1.0.0" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-1.0.0.tgz";
        sha512 = "NM8/P9n3XjXhIZn1lLhkFaACTOURQXjWhV4BA/RnOv8xvgqtqpAX9IO4mRQxSx1Rlo4tqzeqb0sOlruaOy3dug==";
      };
    };
    "keyv-4.5.4" = {
      name = "keyv";
      packageName = "keyv";
      version = "4.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/keyv/-/keyv-4.5.4.tgz";
        sha512 = "oxVHkHR/EJf2CNXnWxRLW6mg7JyCCUcG0DtEGmL2ctUo1PNTin1PUil+r/+4r5MpVgC/fn1kjsx7mjSujKqIpw==";
      };
    };
    "light-my-request-5.11.0" = {
      name = "light-my-request";
      packageName = "light-my-request";
      version = "5.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/light-my-request/-/light-my-request-5.11.0.tgz";
        sha512 = "qkFCeloXCOMpmEdZ/MV91P8AT4fjwFXWaAFz3lUeStM8RcoM1ks4J/F8r1b3r6y/H4u3ACEJ1T+Gv5bopj7oDA==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "lowercase-keys-3.0.0" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-3.0.0.tgz";
        sha512 = "ozCC6gdQ+glXOQsveKD0YsDy8DSQFjDTz4zyzEHNV5+JP5D62LmfDZ6o1cycFx9ouG940M5dE8C8CTewdj2YWQ==";
      };
    };
    "lru-cache-10.2.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "10.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-10.2.0.tgz";
        sha512 = "2bIM8x+VAf6JT4bKAljS1qUWgMsqZRPGJS6FSahIMPVvctcNhyVp7AJu7quxOW9jwkryBReKZY5tY5JYv2n/7Q==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "mime-3.0.0" = {
      name = "mime";
      packageName = "mime";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-3.0.0.tgz";
        sha512 = "jSCU7/VB1loIWBZe14aEYHU/+1UMEHoaO7qxCOVJOw9GgH72VAWppxNcjU+x9a2k3GSIBXNKxXQFqRvvZ7vr3A==";
      };
    };
    "mimic-response-3.1.0" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-3.1.0.tgz";
        sha512 = "z0yWI+4FDrrweS8Zmt4Ej5HdJmky15+L2e6Wgn3+iK5fWzb6T3fhNFq2+MeTRb064c6Wr4N/wv0DzQTjNzHNGQ==";
      };
    };
    "mimic-response-4.0.0" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-4.0.0.tgz";
        sha512 = "e5ISH9xMYU0DzrT+jl8q2ze9D6eWBto+I8CNpe+VI+K2J/F/k3PdkdTdz4wvGVH4NTpo+NRYTVIuMQEMMcsLqg==";
      };
    };
    "minimatch-9.0.3" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "9.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-9.0.3.tgz";
        sha512 = "RHiac9mvaRw0x3AYRgDC1CxAP7HTcNrrECeA8YYJeWnpo+2Q5CegtZjaotWTWxDG3UeGA1coE05iH1mPjT/2mg==";
      };
    };
    "minipass-7.0.4" = {
      name = "minipass";
      packageName = "minipass";
      version = "7.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass/-/minipass-7.0.4.tgz";
        sha512 = "jYofLM5Dam9279rdkWzqHozUo4ybjdZmCsDHePy5V/PbBcVMiSZR97gmAy45aqi8CK1lG2ECd356FU86avfwUQ==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "normalize-url-8.0.0" = {
      name = "normalize-url";
      packageName = "normalize-url";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-url/-/normalize-url-8.0.0.tgz";
        sha512 = "uVFpKhj5MheNBJRTiMZ9pE/7hD1QTeEvugSJW/OmLzAp78PB5O6adfMNTvmfKhXBkvCzC+rqifWcVYpGFwTjnw==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "on-exit-leak-free-2.1.2" = {
      name = "on-exit-leak-free";
      packageName = "on-exit-leak-free";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-exit-leak-free/-/on-exit-leak-free-2.1.2.tgz";
        sha512 = "0eJJY6hXLGf1udHwfNftBqH+g73EU4B504nZeKpz1sYRKafAghwxEJunB2O7rDZkL4PGfsMVnTXZ2EjibbqcsA==";
      };
    };
    "os-paths-7.3.0" = {
      name = "os-paths";
      packageName = "os-paths";
      version = "7.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-paths/-/os-paths-7.3.0.tgz";
        sha512 = "RwE14ySxx9W/wTYzT4F0jUlrhYHLBHVW38os8yN7I9IGmLOpI76NDSlTa7gwHhVnH0IoM6BFp++s5sI3x3dicw==";
      };
    };
    "p-cancelable-3.0.0" = {
      name = "p-cancelable";
      packageName = "p-cancelable";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-cancelable/-/p-cancelable-3.0.0.tgz";
        sha512 = "mlVgR3PGuzlo0MmTdk4cXqXWlwQDLnONTAg6sm62XkMJEiRxN3GL3SffkYvqwonbkJBcrI7Uvv5Zh9yjvn2iUw==";
      };
    };
    "p-limit-3.1.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-3.1.0.tgz";
        sha512 = "TYOanM3wGwNGsZN2cVTYPArw454xnXj5qmWF1bEoAc4+cU/ol7GVh7odevjp1FNHduHc3KZMcFduxU5Xc6uJRQ==";
      };
    };
    "path-key-3.1.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
        sha512 = "ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
      };
    };
    "path-scurry-1.10.1" = {
      name = "path-scurry";
      packageName = "path-scurry";
      version = "1.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-scurry/-/path-scurry-1.10.1.tgz";
        sha512 = "MkhCqzzBEpPvxxQ71Md0b1Kk51W01lrYvlMzSUaIzNsODdd7mqhiimSZlr+VegAz5Z6Vzt9Xg2ttE//XBhH3EQ==";
      };
    };
    "pct-encode-1.0.2" = {
      name = "pct-encode";
      packageName = "pct-encode";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pct-encode/-/pct-encode-1.0.2.tgz";
        sha1 = "b99b7b044d6bd7c39e4839a7a80122ad7515caa5";
      };
    };
    "pino-8.18.0" = {
      name = "pino";
      packageName = "pino";
      version = "8.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pino/-/pino-8.18.0.tgz";
        sha512 = "Mz/gKiRyuXu4HnpHgi1YWdHQCoWMufapzooisvFn78zl4dZciAxS+YeRkUxXl1ee/SzU80YCz1zpECCh4oC6Aw==";
      };
    };
    "pino-abstract-transport-1.1.0" = {
      name = "pino-abstract-transport";
      packageName = "pino-abstract-transport";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pino-abstract-transport/-/pino-abstract-transport-1.1.0.tgz";
        sha512 = "lsleG3/2a/JIWUtf9Q5gUNErBqwIu1tUKTT3dUzaf5DySw9ra1wcqKjJjLX1VTY64Wk1eEOYsVGSaGfCK85ekA==";
      };
    };
    "pino-std-serializers-6.2.2" = {
      name = "pino-std-serializers";
      packageName = "pino-std-serializers";
      version = "6.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pino-std-serializers/-/pino-std-serializers-6.2.2.tgz";
        sha512 = "cHjPPsE+vhj/tnhCy/wiMh3M3z3h/j15zHQX+S9GkTBgqJuTuJzYJ4gUyACLhDaJ7kk9ba9iRDmbH2tJU03OiA==";
      };
    };
    "process-0.11.10" = {
      name = "process";
      packageName = "process";
      version = "0.11.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/process/-/process-0.11.10.tgz";
        sha512 = "cdGef/drWFoydD1JsMzuFf8100nZl+GT+yacc2bEced5f9Rjk4z+WtFUTBu9PhOi9j/jfmBPu0mMEY4wIdAF8A==";
      };
    };
    "process-warning-2.3.2" = {
      name = "process-warning";
      packageName = "process-warning";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-warning/-/process-warning-2.3.2.tgz";
        sha512 = "n9wh8tvBe5sFmsqlg+XQhaQLumwpqoAUruLwjCopgTmUBjJ/fjtBsJzKleCaIGBOMXYEhp1YfKl4d7rJ5ZKJGA==";
      };
    };
    "process-warning-3.0.0" = {
      name = "process-warning";
      packageName = "process-warning";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-warning/-/process-warning-3.0.0.tgz";
        sha512 = "mqn0kFRl0EoqhnL0GQ0veqFHyIN1yig9RHh/InzORTUiZHFRAur+aMtRkELNwGs9aNwKS6tg/An4NYBPGwvtzQ==";
      };
    };
    "proxy-addr-2.0.7" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "2.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-2.0.7.tgz";
        sha512 = "llQsMLSUDUPT44jdrU/O37qlnifitDP+ZwrmmZcoSKyLKvtZxpyV0n2/bD/N4tBAAZ/gJEdZU7KMraoK1+XYAg==";
      };
    };
    "punycode-2.1.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.1.1.tgz";
        sha512 = "XRsRjdf+j5ml+y/6GKHPZbrF/8p2Yga0JPtdqTIY2Xe5ohJPD9saDJJLPvp9+NSBprVvevdXZybnj2cv8OEd0A==";
      };
    };
    "quick-format-unescaped-4.0.4" = {
      name = "quick-format-unescaped";
      packageName = "quick-format-unescaped";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/quick-format-unescaped/-/quick-format-unescaped-4.0.4.tgz";
        sha512 = "tYC1Q1hgyRuHgloV/YXs2w15unPVh8qfu/qCTfhTYamaw7fyhumKa2yGpdSo87vY32rIclj+4fWYQXUMs9EHvg==";
      };
    };
    "quick-lru-5.1.1" = {
      name = "quick-lru";
      packageName = "quick-lru";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/quick-lru/-/quick-lru-5.1.1.tgz";
        sha512 = "WuyALRjWPDGtt/wzJiadO5AXY+8hZ80hVpe6MyivgraREW751X3SbhRvG3eLKOYN+8VEvqLcf3wdnt44Z4S4SA==";
      };
    };
    "ramda-0.28.0" = {
      name = "ramda";
      packageName = "ramda";
      version = "0.28.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ramda/-/ramda-0.28.0.tgz";
        sha512 = "9QnLuG/kPVgWvMQ4aODhsBUFKOUmnbUnsSXACv+NCQZcHbeb+v8Lodp8OVxtRULN1/xOyYLLaL6npE6dMq5QTA==";
      };
    };
    "react-17.0.2" = {
      name = "react";
      packageName = "react";
      version = "17.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-17.0.2.tgz";
        sha512 = "gnhPt75i/dq/z3/6q/0asP78D0u592D5L1pd7M8P+dck6Fu/jJeL6iVVK23fptSUZj8Vjf++7wXA8UNclGQcbA==";
      };
    };
    "react-dom-17.0.2" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "17.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-17.0.2.tgz";
        sha512 = "s4h96KtLDUQlsENhMn1ar8t2bEa+q/YAtj8pPPdIjPDGBDIVNsrD9aXNWqspUe6AzKCIG0C1HZZLqLV7qpOBGA==";
      };
    };
    "readable-stream-4.5.2" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "4.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-4.5.2.tgz";
        sha512 = "yjavECdqeZ3GLXNgRXgeQEdz9fvDDkNKyHnbHRFtOr7/LcfgBcmct7t/ET+HaCTqfh06OzoAxrkN/IfjJBVe+g==";
      };
    };
    "real-require-0.2.0" = {
      name = "real-require";
      packageName = "real-require";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/real-require/-/real-require-0.2.0.tgz";
        sha512 = "57frrGM/OCTLqLOAh0mhVA9VBMHd+9U7Zb2THMGdBUoZVOtGbJzjxsYGDJ3A9AYYCP4hn6y1TVbaOfzWtm5GFg==";
      };
    };
    "require-from-string-2.0.2" = {
      name = "require-from-string";
      packageName = "require-from-string";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz";
        sha512 = "Xf0nWe6RseziFMu+Ap9biiUbmplq6S9/p+7w7YXP/JBHhrUDDUhwa+vANyubuqfZWTveU//DYVGsDG7RKL/vEw==";
      };
    };
    "resolve-alpn-1.2.1" = {
      name = "resolve-alpn";
      packageName = "resolve-alpn";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-alpn/-/resolve-alpn-1.2.1.tgz";
        sha512 = "0a1F4l73/ZFZOakJnQ3FvkJ2+gSTQWz/r2KE5OdDY0TxPm5h4GkqkWWfM47T7HsbnOtcJVEF4epCVy6u7Q3K+g==";
      };
    };
    "responselike-3.0.0" = {
      name = "responselike";
      packageName = "responselike";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/responselike/-/responselike-3.0.0.tgz";
        sha512 = "40yHxbNcl2+rzXvZuVkrYohathsSJlMTXKryG5y8uciHv1+xDLHQpgjG64JUO9nrEq2jGLH6IZ8BcZyw3wrweg==";
      };
    };
    "ret-0.2.2" = {
      name = "ret";
      packageName = "ret";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ret/-/ret-0.2.2.tgz";
        sha512 = "M0b3YWQs7R3Z917WRQy1HHA7Ba7D8hvZg6UE5mLykJxQVE2ju0IXbGlaHPPlkY+WN7wFP+wUMXmBFA0aV6vYGQ==";
      };
    };
    "reusify-1.0.4" = {
      name = "reusify";
      packageName = "reusify";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/reusify/-/reusify-1.0.4.tgz";
        sha512 = "U9nH88a3fc/ekCF1l0/UP1IosiuIjyTh7hBvXVMHYgVcfGvt897Xguj2UOLDeI5BG2m7/uwyaLVT6fbtCwTyzw==";
      };
    };
    "rfdc-1.3.1" = {
      name = "rfdc";
      packageName = "rfdc";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rfdc/-/rfdc-1.3.1.tgz";
        sha512 = "r5a3l5HzYlIC68TpmYKlxWjmOP6wiPJ1vWv2HeLhNsRZMrCkxeqxiHlQ21oXmQ4F3SiryXBHhAD7JZqvOJjFmg==";
      };
    };
    "rxjs-7.5.5" = {
      name = "rxjs";
      packageName = "rxjs";
      version = "7.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/rxjs/-/rxjs-7.5.5.tgz";
        sha512 = "sy+H0pQofO95VDmFLzyaw9xNJU4KTRSwQIGM6+iG3SypAtCiLDzpeG8sJrNCWn2Up9km+KhkvTdbkrdy+yzZdw==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safe-regex2-2.0.0" = {
      name = "safe-regex2";
      packageName = "safe-regex2";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-regex2/-/safe-regex2-2.0.0.tgz";
        sha512 = "PaUSFsUaNNuKwkBijoAPHAK6/eM6VirvyPWlZ7BAQy4D+hCvh4B6lIG+nPdhbFfIbP+gTGBcrdsOaUs0F+ZBOQ==";
      };
    };
    "safe-stable-stringify-2.4.3" = {
      name = "safe-stable-stringify";
      packageName = "safe-stable-stringify";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-stable-stringify/-/safe-stable-stringify-2.4.3.tgz";
        sha512 = "e2bDA2WJT0wxseVd4lsDP4+3ONX6HpMXQa1ZhFQ7SU+GjvORCmShbCMltrtIDfkYhVHrOcPtj+KhmDBdPdZD1g==";
      };
    };
    "scheduler-0.20.2" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.20.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.20.2.tgz";
        sha512 = "2eWfGgAqqWFGqtdMmcL5zCMK1U8KlXv8SQFGglL3CEtd0aDVDWgeF/YoCmvln55m5zSk3J/20hTaSBeSObsQDQ==";
      };
    };
    "secure-json-parse-2.7.0" = {
      name = "secure-json-parse";
      packageName = "secure-json-parse";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/secure-json-parse/-/secure-json-parse-2.7.0.tgz";
        sha512 = "6aU+Rwsezw7VR8/nyvKTx8QpWH9FrcYiXXlqC4z5d5XQBDRqtbfsRjnwGyqbi3gddNtWHuEk9OANUotL26qKUw==";
      };
    };
    "semver-7.5.4" = {
      name = "semver";
      packageName = "semver";
      version = "7.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.5.4.tgz";
        sha512 = "1bCSESV6Pv+i21Hvpxp3Dx+pSD8lIPt8uVjRrxAUt/nbswYc+tK6Y2btiULjd4+fnq15PX+nqQDC7Oft7WkwcA==";
      };
    };
    "set-cookie-parser-2.6.0" = {
      name = "set-cookie-parser";
      packageName = "set-cookie-parser";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-cookie-parser/-/set-cookie-parser-2.6.0.tgz";
        sha512 = "RVnVQxTXuerk653XfuliOxBP81Sf0+qfQE73LIYKcyMYHG94AuH0kgrQpRDuTZnSmjpysHmzxJXKNfa6PjFhyQ==";
      };
    };
    "setprototypeof-1.2.0" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.2.0.tgz";
        sha512 = "E5LDX7Wrp85Kil5bhZv46j8jOeboKq5JMmYM3gVGdGH8xFpPWXUMsNrlODCrkoxMEeNi/XZIwuRvY4XNwYMJpw==";
      };
    };
    "shebang-command-2.0.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
        sha512 = "kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      };
    };
    "shebang-regex-3.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
        sha512 = "7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
      };
    };
    "signal-exit-4.1.0" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-4.1.0.tgz";
        sha512 = "bzyZ1e88w9O1iNJbKnOlvYTrWPDl46O1bG0D3XInv+9tkPrxrN8jUUTiFlDkkmKWgn1M6CfIA13SuGqOa9Korw==";
      };
    };
    "sonic-boom-3.8.0" = {
      name = "sonic-boom";
      packageName = "sonic-boom";
      version = "3.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sonic-boom/-/sonic-boom-3.8.0.tgz";
        sha512 = "ybz6OYOUjoQQCQ/i4LU8kaToD8ACtYP+Cj5qd2AO36bwbdewxWJ3ArmJ2cr6AvxlL2o0PqnCcPGUgkILbfkaCA==";
      };
    };
    "split2-4.2.0" = {
      name = "split2";
      packageName = "split2";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/split2/-/split2-4.2.0.tgz";
        sha512 = "UcjcJOWknrNkF6PLX83qcHM6KHgVKNkV62Y8a5uYDVv9ydGQVwAHMKqHdJje1VTWpljG0WYpCDhrCdAOYH4TWg==";
      };
    };
    "statuses-2.0.1" = {
      name = "statuses";
      packageName = "statuses";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-2.0.1.tgz";
        sha512 = "RwNA9Z/7PrK06rYLIzFMlaF+l73iwpzsqRIFgbMLbTcLD6cOao82TaWefPXQvB2fOC4AjuYSEndS7N/mTCbkdQ==";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "string-width-5.1.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-5.1.2.tgz";
        sha512 = "HnLOCR3vjcY8beoNLtcjZ5/nxn2afmME6lhrDrebokqMap+XbeW8n9TXpPDOqdGK5qcI3oT0GKTW6wC7EMiVqA==";
      };
    };
    "string-width-cjs-npm:string-width@4.2.3" = {
      name = "string-width-cjs";
      packageName = "string-width-cjs";
      version = "npm:string-width@4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "strip-ansi-7.1.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-7.1.0.tgz";
        sha512 = "iq6eVVI64nQQTRYq2KtEg2d2uU7LElhTJwsH4YzIHZshxlgZms/wIc4VoDQTlG/IvVIrBKG06CrZnp0qv7hkcQ==";
      };
    };
    "strip-ansi-cjs-npm:strip-ansi@6.0.1" = {
      name = "strip-ansi-cjs";
      packageName = "strip-ansi-cjs";
      version = "npm:strip-ansi@6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "thread-stream-2.4.1" = {
      name = "thread-stream";
      packageName = "thread-stream";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/thread-stream/-/thread-stream-2.4.1.tgz";
        sha512 = "d/Ex2iWd1whipbT681JmTINKw0ZwOUBZm7+Gjs64DHuX34mmw8vJL2bFAaNacaW72zYiTJxSHi5abUuOi5nsfg==";
      };
    };
    "toad-cache-3.7.0" = {
      name = "toad-cache";
      packageName = "toad-cache";
      version = "3.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/toad-cache/-/toad-cache-3.7.0.tgz";
        sha512 = "/m8M+2BJUpoJdgAHoG+baCwBT+tf2VraSfkBgl0Y00qIWt41DJ8R5B8nsEw0I58YwF5IZH6z24/2TobDKnqSWw==";
      };
    };
    "toidentifier-1.0.1" = {
      name = "toidentifier";
      packageName = "toidentifier";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/toidentifier/-/toidentifier-1.0.1.tgz";
        sha512 = "o5sSPKEkg/DIQNmH43V0/uerLrpzVedkUh8tGNvaeXpfpuwjKenlSox/2O/BTlZUtEe+JG7s5YhEz608PlAHRA==";
      };
    };
    "tslib-2.4.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.4.0.tgz";
        sha512 = "d6xOpEDfsi2CZVlPQzGeux8XMwLT9hssAsaPYExaQMuYskwb+x1x7J371tWlbBdWHroy99KnVB6qIkUbs5X3UQ==";
      };
    };
    "uri-js-4.4.1" = {
      name = "uri-js";
      packageName = "uri-js";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-js/-/uri-js-4.4.1.tgz";
        sha512 = "7rKUyy33Q1yc98pQ1DAmLtwX109F7TIfWlW1Ydo8Wl1ii1SeHieeh0HHfPeL2fMXK6z0s8ecKs9frCuLJvndBg==";
      };
    };
    "uri-template-2.0.0" = {
      name = "uri-template";
      packageName = "uri-template";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-template/-/uri-template-2.0.0.tgz";
        sha512 = "r/i44nPoo0ktEZDjx+hxp9PSjQuBBfsd6RgCRuuMqCP0FZEp+YE0SpihThI4UGc5ePqQEFsdyZc7UVlowp+LLw==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "wrap-ansi-8.1.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-8.1.0.tgz";
        sha512 = "si7QWI6zUMq56bESFvagtmzMdGOtoxfR+Sez11Mobfc7tm+VkUckk9bW2UeffTGVUbOksxmSw0AA2gs8g71NCQ==";
      };
    };
    "wrap-ansi-cjs-npm:wrap-ansi@7.0.0" = {
      name = "wrap-ansi-cjs";
      packageName = "wrap-ansi-cjs";
      version = "npm:wrap-ansi@7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz";
        sha512 = "YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==";
      };
    };
    "xdg-portable-10.5.1" = {
      name = "xdg-portable";
      packageName = "xdg-portable";
      version = "10.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xdg-portable/-/xdg-portable-10.5.1.tgz";
        sha512 = "dKX7yn1jgKqh4GENubRidDpDoaRmwwoiEph2JAcDUD6n3/5ROy5rQo42MX8iIl0UCUhVpsoU2jth5DtdvOATvA==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "yocto-queue-0.1.0" = {
      name = "yocto-queue";
      packageName = "yocto-queue";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yocto-queue/-/yocto-queue-0.1.0.tgz";
        sha512 = "rVksvsnNCdJ/ohGc6xgPwyN8eheCxsiLM8mxuE/t/mOVqJewPuO1miLpTHQiRgTKCLexL4MeAFVagts7HmNZ2Q==";
      };
    };
  };
  args = {
    name = "bbrf-radio";
    packageName = "bbrf-radio";
    version = "0.8.0";
    src = ./.;
    dependencies = [
      sources."@esbuild/android-arm-0.18.8"
      sources."@esbuild/android-arm64-0.18.8"
      sources."@esbuild/android-x64-0.18.8"
      sources."@esbuild/darwin-arm64-0.18.8"
      sources."@esbuild/darwin-x64-0.18.8"
      sources."@esbuild/freebsd-arm64-0.18.8"
      sources."@esbuild/freebsd-x64-0.18.8"
      sources."@esbuild/linux-arm-0.18.8"
      sources."@esbuild/linux-arm64-0.18.8"
      sources."@esbuild/linux-ia32-0.18.8"
      sources."@esbuild/linux-loong64-0.18.8"
      sources."@esbuild/linux-mips64el-0.18.8"
      sources."@esbuild/linux-ppc64-0.18.8"
      sources."@esbuild/linux-riscv64-0.18.8"
      sources."@esbuild/linux-s390x-0.18.8"
      sources."@esbuild/linux-x64-0.18.8"
      sources."@esbuild/netbsd-x64-0.18.8"
      sources."@esbuild/openbsd-x64-0.18.8"
      sources."@esbuild/sunos-x64-0.18.8"
      sources."@esbuild/win32-arm64-0.18.8"
      sources."@esbuild/win32-ia32-0.18.8"
      sources."@esbuild/win32-x64-0.18.8"
      sources."@fastify/accept-negotiator-1.1.0"
      (sources."@fastify/ajv-compiler-3.5.0" // {
        dependencies = [
          sources."ajv-8.12.0"
          sources."json-schema-traverse-1.0.0"
        ];
      })
      sources."@fastify/deepmerge-1.3.0"
      sources."@fastify/error-3.4.1"
      sources."@fastify/fast-json-stringify-compiler-4.3.0"
      sources."@fastify/send-2.1.0"
      (sources."@fastify/static-7.0.0" // {
        dependencies = [
          sources."brace-expansion-2.0.1"
          sources."glob-10.3.10"
          sources."minimatch-9.0.3"
        ];
      })
      (sources."@isaacs/cliui-8.0.2" // {
        dependencies = [
          sources."ansi-regex-6.0.1"
          sources."strip-ansi-7.1.0"
        ];
      })
      sources."@lukeed/ms-2.0.2"
      sources."@pkgjs/parseargs-0.11.0"
      sources."@sindresorhus/is-5.6.0"
      sources."@szmarczak/http-timer-5.0.1"
      sources."@types/http-cache-semantics-4.0.4"
      sources."abort-controller-3.0.0"
      sources."abstract-logging-2.0.1"
      (sources."ajv-formats-2.1.1" // {
        dependencies = [
          sources."ajv-8.12.0"
          sources."json-schema-traverse-1.0.0"
        ];
      })
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-4.3.0"
      sources."archy-1.0.0"
      sources."atomic-sleep-1.0.0"
      sources."avvio-8.2.1"
      sources."balanced-match-1.0.2"
      sources."base64-js-1.5.1"
      sources."buffer-6.0.3"
      sources."cacheable-lookup-7.0.0"
      sources."cacheable-request-10.2.14"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."content-disposition-0.5.4"
      sources."cookie-0.5.0"
      sources."cross-spawn-7.0.3"
      (sources."debug-4.3.4" // {
        dependencies = [
          sources."ms-2.1.2"
        ];
      })
      (sources."decompress-response-6.0.0" // {
        dependencies = [
          sources."mimic-response-3.1.0"
        ];
      })
      sources."defer-to-connect-2.0.1"
      sources."depd-2.0.0"
      sources."eastasianwidth-0.2.0"
      sources."emoji-regex-9.2.2"
      sources."esbuild-0.18.8"
      sources."escape-html-1.0.3"
      sources."event-target-shim-5.0.1"
      sources."events-3.3.0"
      sources."fast-content-type-parse-1.1.0"
      sources."fast-decode-uri-component-1.0.1"
      sources."fast-deep-equal-3.1.3"
      (sources."fast-json-stringify-5.11.1" // {
        dependencies = [
          sources."ajv-8.12.0"
          sources."json-schema-traverse-1.0.0"
        ];
      })
      sources."fast-querystring-1.1.2"
      sources."fast-redact-3.3.0"
      sources."fast-uri-2.3.0"
      (sources."fastify-4.26.0" // {
        dependencies = [
          sources."semver-7.5.4"
        ];
      })
      sources."fastify-plugin-4.5.1"
      sources."fastq-1.17.0"
      sources."find-my-way-8.1.0"
      sources."foreground-child-3.1.1"
      sources."form-data-encoder-2.1.4"
      sources."forwarded-0.2.0"
      sources."get-stream-6.0.1"
      sources."got-12.6.1"
      sources."http-cache-semantics-4.1.1"
      sources."http-errors-2.0.0"
      sources."http2-wrapper-2.1.11"
      sources."ieee754-1.2.1"
      sources."inherits-2.0.4"
      sources."ipaddr.js-1.9.1"
      sources."is-fullwidth-code-point-3.0.0"
      sources."isexe-2.0.0"
      sources."jackspeak-2.3.6"
      sources."js-tokens-4.0.0"
      sources."json-buffer-3.0.1"
      sources."json-schema-ref-resolver-1.0.1"
      sources."keyv-4.5.4"
      (sources."light-my-request-5.11.0" // {
        dependencies = [
          sources."process-warning-2.3.2"
        ];
      })
      sources."loose-envify-1.4.0"
      sources."lowercase-keys-3.0.0"
      sources."lru-cache-6.0.0"
      sources."mime-3.0.0"
      sources."mimic-response-4.0.0"
      sources."minipass-7.0.4"
      sources."normalize-url-8.0.0"
      sources."object-assign-4.1.1"
      sources."on-exit-leak-free-2.1.2"
      sources."os-paths-7.3.0"
      sources."p-cancelable-3.0.0"
      sources."p-limit-3.1.0"
      sources."path-key-3.1.1"
      (sources."path-scurry-1.10.1" // {
        dependencies = [
          sources."lru-cache-10.2.0"
        ];
      })
      sources."pct-encode-1.0.2"
      sources."pino-8.18.0"
      (sources."pino-abstract-transport-1.1.0" // {
        dependencies = [
          sources."readable-stream-4.5.2"
        ];
      })
      sources."pino-std-serializers-6.2.2"
      sources."process-0.11.10"
      sources."process-warning-3.0.0"
      sources."proxy-addr-2.0.7"
      sources."punycode-2.1.1"
      sources."quick-format-unescaped-4.0.4"
      sources."quick-lru-5.1.1"
      sources."ramda-0.28.0"
      sources."react-17.0.2"
      sources."react-dom-17.0.2"
      sources."real-require-0.2.0"
      sources."require-from-string-2.0.2"
      sources."resolve-alpn-1.2.1"
      sources."responselike-3.0.0"
      sources."ret-0.2.2"
      sources."reusify-1.0.4"
      sources."rfdc-1.3.1"
      sources."rxjs-7.5.5"
      sources."safe-buffer-5.2.1"
      sources."safe-regex2-2.0.0"
      sources."safe-stable-stringify-2.4.3"
      sources."scheduler-0.20.2"
      sources."secure-json-parse-2.7.0"
      sources."set-cookie-parser-2.6.0"
      sources."setprototypeof-1.2.0"
      sources."shebang-command-2.0.0"
      sources."shebang-regex-3.0.0"
      sources."signal-exit-4.1.0"
      sources."sonic-boom-3.8.0"
      sources."split2-4.2.0"
      sources."statuses-2.0.1"
      (sources."string-width-5.1.2" // {
        dependencies = [
          sources."ansi-regex-6.0.1"
          sources."strip-ansi-7.1.0"
        ];
      })
      (sources."string-width-cjs-npm:string-width@4.2.3" // {
        dependencies = [
          sources."emoji-regex-8.0.0"
        ];
      })
      sources."string_decoder-1.3.0"
      sources."strip-ansi-6.0.1"
      sources."strip-ansi-cjs-npm:strip-ansi@6.0.1"
      sources."thread-stream-2.4.1"
      sources."toad-cache-3.7.0"
      sources."toidentifier-1.0.1"
      sources."tslib-2.4.0"
      sources."uri-js-4.4.1"
      sources."uri-template-2.0.0"
      sources."which-2.0.2"
      (sources."wrap-ansi-8.1.0" // {
        dependencies = [
          sources."ansi-regex-6.0.1"
          sources."ansi-styles-6.2.1"
          sources."strip-ansi-7.1.0"
        ];
      })
      (sources."wrap-ansi-cjs-npm:wrap-ansi@7.0.0" // {
        dependencies = [
          sources."emoji-regex-8.0.0"
          sources."string-width-4.2.3"
        ];
      })
      sources."xdg-portable-10.5.1"
      sources."yallist-4.0.0"
      sources."yocto-queue-0.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      license = "GPL-2.0-only";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
